//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.02 at 04:34:44 PM MSK 
//


package org.amanzi.neo.model.distribution.xml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for distribution complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="distribution">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="data" type="{http://www.example.org/DistributionXMLSchema}data"/>
 *         &lt;element name="bars" type="{http://www.example.org/DistributionXMLSchema}bars"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "distribution", propOrder = {

})
public class Distribution {

    @XmlElement(required = true)
    protected Data data;
    @XmlElement(required = true)
    protected Bars bars;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Data }
     *     
     */
    public Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    public void setData(Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the bars property.
     * 
     * @return
     *     possible object is
     *     {@link Bars }
     *     
     */
    public Bars getBars() {
        return bars;
    }

    /**
     * Sets the value of the bars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bars }
     *     
     */
    public void setBars(Bars value) {
        this.bars = value;
    }

}
