
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "CellChangeOrderFromUTRANFailure_r3_IEs", isSet = false )
    public class CellChangeOrderFromUTRANFailure_r3_IEs implements IASN1PreparedElement {
            
        @ASN1Element ( name = "rrc-TransactionIdentifier", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RRC_TransactionIdentifier rrc_TransactionIdentifier = null;
                
  
        @ASN1Element ( name = "dummy", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private IntegrityProtectionModeInfo dummy = null;
                
  
        @ASN1Element ( name = "interRAT-ChangeFailureCause", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private InterRAT_ChangeFailureCause interRAT_ChangeFailureCause = null;
                
  
        
        public RRC_TransactionIdentifier getRrc_TransactionIdentifier () {
            return this.rrc_TransactionIdentifier;
        }

        

        public void setRrc_TransactionIdentifier (RRC_TransactionIdentifier value) {
            this.rrc_TransactionIdentifier = value;
        }
        
  
        
        public IntegrityProtectionModeInfo getDummy () {
            return this.dummy;
        }

        
        public boolean isDummyPresent () {
            return this.dummy != null;
        }
        

        public void setDummy (IntegrityProtectionModeInfo value) {
            this.dummy = value;
        }
        
  
        
        public InterRAT_ChangeFailureCause getInterRAT_ChangeFailureCause () {
            return this.interRAT_ChangeFailureCause;
        }

        

        public void setInterRAT_ChangeFailureCause (InterRAT_ChangeFailureCause value) {
            this.interRAT_ChangeFailureCause = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CellChangeOrderFromUTRANFailure_r3_IEs.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            