
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "InterRAT_ChangeFailureCause" )
    public class InterRAT_ChangeFailureCause implements IASN1PreparedElement {
            
        @ASN1Null ( name = "configurationUnacceptable" ) 
    
        @ASN1Element ( name = "configurationUnacceptable", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject configurationUnacceptable = null;
                
  
        @ASN1Null ( name = "physicalChannelFailure" ) 
    
        @ASN1Element ( name = "physicalChannelFailure", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject physicalChannelFailure = null;
                
  
        @ASN1Element ( name = "protocolError", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private ProtocolErrorInformation protocolError = null;
                
  
        @ASN1Null ( name = "unspecified" ) 
    
        @ASN1Element ( name = "unspecified", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject unspecified = null;
                
  
        @ASN1Null ( name = "spare4" ) 
    
        @ASN1Element ( name = "spare4", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject spare4 = null;
                
  
        @ASN1Null ( name = "spare3" ) 
    
        @ASN1Element ( name = "spare3", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject spare3 = null;
                
  
        @ASN1Null ( name = "spare2" ) 
    
        @ASN1Element ( name = "spare2", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject spare2 = null;
                
  
        @ASN1Null ( name = "spare1" ) 
    
        @ASN1Element ( name = "spare1", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject spare1 = null;
                
  
        
        public org.bn.types.NullObject getConfigurationUnacceptable () {
            return this.configurationUnacceptable;
        }

        public boolean isConfigurationUnacceptableSelected () {
            return this.configurationUnacceptable != null;
        }

        private void setConfigurationUnacceptable (org.bn.types.NullObject value) {
            this.configurationUnacceptable = value;
        }

        
        public void selectConfigurationUnacceptable () {
            selectConfigurationUnacceptable (new org.bn.types.NullObject());
	}
	
        public void selectConfigurationUnacceptable (org.bn.types.NullObject value) {
            this.configurationUnacceptable = value;
            
                    setPhysicalChannelFailure(null);
                
                    setProtocolError(null);
                
                    setUnspecified(null);
                
                    setSpare4(null);
                
                    setSpare3(null);
                
                    setSpare2(null);
                
                    setSpare1(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getPhysicalChannelFailure () {
            return this.physicalChannelFailure;
        }

        public boolean isPhysicalChannelFailureSelected () {
            return this.physicalChannelFailure != null;
        }

        private void setPhysicalChannelFailure (org.bn.types.NullObject value) {
            this.physicalChannelFailure = value;
        }

        
        public void selectPhysicalChannelFailure () {
            selectPhysicalChannelFailure (new org.bn.types.NullObject());
	}
	
        public void selectPhysicalChannelFailure (org.bn.types.NullObject value) {
            this.physicalChannelFailure = value;
            
                    setConfigurationUnacceptable(null);
                
                    setProtocolError(null);
                
                    setUnspecified(null);
                
                    setSpare4(null);
                
                    setSpare3(null);
                
                    setSpare2(null);
                
                    setSpare1(null);
                            
        }

        
  
        
        public ProtocolErrorInformation getProtocolError () {
            return this.protocolError;
        }

        public boolean isProtocolErrorSelected () {
            return this.protocolError != null;
        }

        private void setProtocolError (ProtocolErrorInformation value) {
            this.protocolError = value;
        }

        
        public void selectProtocolError (ProtocolErrorInformation value) {
            this.protocolError = value;
            
                    setConfigurationUnacceptable(null);
                
                    setPhysicalChannelFailure(null);
                
                    setUnspecified(null);
                
                    setSpare4(null);
                
                    setSpare3(null);
                
                    setSpare2(null);
                
                    setSpare1(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getUnspecified () {
            return this.unspecified;
        }

        public boolean isUnspecifiedSelected () {
            return this.unspecified != null;
        }

        private void setUnspecified (org.bn.types.NullObject value) {
            this.unspecified = value;
        }

        
        public void selectUnspecified () {
            selectUnspecified (new org.bn.types.NullObject());
	}
	
        public void selectUnspecified (org.bn.types.NullObject value) {
            this.unspecified = value;
            
                    setConfigurationUnacceptable(null);
                
                    setPhysicalChannelFailure(null);
                
                    setProtocolError(null);
                
                    setSpare4(null);
                
                    setSpare3(null);
                
                    setSpare2(null);
                
                    setSpare1(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getSpare4 () {
            return this.spare4;
        }

        public boolean isSpare4Selected () {
            return this.spare4 != null;
        }

        private void setSpare4 (org.bn.types.NullObject value) {
            this.spare4 = value;
        }

        
        public void selectSpare4 () {
            selectSpare4 (new org.bn.types.NullObject());
	}
	
        public void selectSpare4 (org.bn.types.NullObject value) {
            this.spare4 = value;
            
                    setConfigurationUnacceptable(null);
                
                    setPhysicalChannelFailure(null);
                
                    setProtocolError(null);
                
                    setUnspecified(null);
                
                    setSpare3(null);
                
                    setSpare2(null);
                
                    setSpare1(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getSpare3 () {
            return this.spare3;
        }

        public boolean isSpare3Selected () {
            return this.spare3 != null;
        }

        private void setSpare3 (org.bn.types.NullObject value) {
            this.spare3 = value;
        }

        
        public void selectSpare3 () {
            selectSpare3 (new org.bn.types.NullObject());
	}
	
        public void selectSpare3 (org.bn.types.NullObject value) {
            this.spare3 = value;
            
                    setConfigurationUnacceptable(null);
                
                    setPhysicalChannelFailure(null);
                
                    setProtocolError(null);
                
                    setUnspecified(null);
                
                    setSpare4(null);
                
                    setSpare2(null);
                
                    setSpare1(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getSpare2 () {
            return this.spare2;
        }

        public boolean isSpare2Selected () {
            return this.spare2 != null;
        }

        private void setSpare2 (org.bn.types.NullObject value) {
            this.spare2 = value;
        }

        
        public void selectSpare2 () {
            selectSpare2 (new org.bn.types.NullObject());
	}
	
        public void selectSpare2 (org.bn.types.NullObject value) {
            this.spare2 = value;
            
                    setConfigurationUnacceptable(null);
                
                    setPhysicalChannelFailure(null);
                
                    setProtocolError(null);
                
                    setUnspecified(null);
                
                    setSpare4(null);
                
                    setSpare3(null);
                
                    setSpare1(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getSpare1 () {
            return this.spare1;
        }

        public boolean isSpare1Selected () {
            return this.spare1 != null;
        }

        private void setSpare1 (org.bn.types.NullObject value) {
            this.spare1 = value;
        }

        
        public void selectSpare1 () {
            selectSpare1 (new org.bn.types.NullObject());
	}
	
        public void selectSpare1 (org.bn.types.NullObject value) {
            this.spare1 = value;
            
                    setConfigurationUnacceptable(null);
                
                    setPhysicalChannelFailure(null);
                
                    setProtocolError(null);
                
                    setUnspecified(null);
                
                    setSpare4(null);
                
                    setSpare3(null);
                
                    setSpare2(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(InterRAT_ChangeFailureCause.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            