
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "MaxSimultaneousTransChsDL"
    )
    public class MaxSimultaneousTransChsDL implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "e4", hasTag = true , tag = 0 )
            e4 , 
            @ASN1EnumItem ( name = "e8", hasTag = true , tag = 1 )
            e8 , 
            @ASN1EnumItem ( name = "e16", hasTag = true , tag = 2 )
            e16 , 
            @ASN1EnumItem ( name = "e32", hasTag = true , tag = 3 )
            e32 , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MaxSimultaneousTransChsDL.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            