
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "MeasurementReport_v390ext", isSet = false )
    public class MeasurementReport_v390ext implements IASN1PreparedElement {
            
        @ASN1Element ( name = "measuredResults-v390ext", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private MeasuredResults_v390ext measuredResults_v390ext = null;
                
  
        
        public MeasuredResults_v390ext getMeasuredResults_v390ext () {
            return this.measuredResults_v390ext;
        }

        
        public boolean isMeasuredResults_v390extPresent () {
            return this.measuredResults_v390ext != null;
        }
        

        public void setMeasuredResults_v390ext (MeasuredResults_v390ext value) {
            this.measuredResults_v390ext = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MeasurementReport_v390ext.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            