
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "MeasurementCapabilityExt", isSet = false )
    public class MeasurementCapabilityExt implements IASN1PreparedElement {
            
        @ASN1Element ( name = "compressedModeMeasCapabFDDList", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private CompressedModeMeasCapabFDDList compressedModeMeasCapabFDDList = null;
                
  
        @ASN1Element ( name = "compressedModeMeasCapabTDDList", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CompressedModeMeasCapabTDDList compressedModeMeasCapabTDDList = null;
                
  
        @ASN1Element ( name = "compressedModeMeasCapabGSMList", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CompressedModeMeasCapabGSMList compressedModeMeasCapabGSMList = null;
                
  
        @ASN1Element ( name = "compressedModeMeasCapabMC", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private CompressedModeMeasCapabMC compressedModeMeasCapabMC = null;
                
  
        
        public CompressedModeMeasCapabFDDList getCompressedModeMeasCapabFDDList () {
            return this.compressedModeMeasCapabFDDList;
        }

        

        public void setCompressedModeMeasCapabFDDList (CompressedModeMeasCapabFDDList value) {
            this.compressedModeMeasCapabFDDList = value;
        }
        
  
        
        public CompressedModeMeasCapabTDDList getCompressedModeMeasCapabTDDList () {
            return this.compressedModeMeasCapabTDDList;
        }

        
        public boolean isCompressedModeMeasCapabTDDListPresent () {
            return this.compressedModeMeasCapabTDDList != null;
        }
        

        public void setCompressedModeMeasCapabTDDList (CompressedModeMeasCapabTDDList value) {
            this.compressedModeMeasCapabTDDList = value;
        }
        
  
        
        public CompressedModeMeasCapabGSMList getCompressedModeMeasCapabGSMList () {
            return this.compressedModeMeasCapabGSMList;
        }

        
        public boolean isCompressedModeMeasCapabGSMListPresent () {
            return this.compressedModeMeasCapabGSMList != null;
        }
        

        public void setCompressedModeMeasCapabGSMList (CompressedModeMeasCapabGSMList value) {
            this.compressedModeMeasCapabGSMList = value;
        }
        
  
        
        public CompressedModeMeasCapabMC getCompressedModeMeasCapabMC () {
            return this.compressedModeMeasCapabMC;
        }

        
        public boolean isCompressedModeMeasCapabMCPresent () {
            return this.compressedModeMeasCapabMC != null;
        }
        

        public void setCompressedModeMeasCapabMC (CompressedModeMeasCapabMC value) {
            this.compressedModeMeasCapabMC = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MeasurementCapabilityExt.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            