
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "MultiRAT_Capability", isSet = false )
    public class MultiRAT_Capability implements IASN1PreparedElement {
            @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "supportOfGSM", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean supportOfGSM = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "supportOfMulticarrier", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean supportOfMulticarrier = null;
                
  
        
        public Boolean getSupportOfGSM () {
            return this.supportOfGSM;
        }

        

        public void setSupportOfGSM (Boolean value) {
            this.supportOfGSM = value;
        }
        
  
        
        public Boolean getSupportOfMulticarrier () {
            return this.supportOfMulticarrier;
        }

        

        public void setSupportOfMulticarrier (Boolean value) {
            this.supportOfMulticarrier = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MultiRAT_Capability.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            