
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "TimeslotISCP_List" )
    public class TimeslotISCP_List implements IASN1PreparedElement {
                
            @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 14L 
		
	   )
	   
            @ASN1SequenceOf( name = "TimeslotISCP-List" , isSetOf = false)
	    private java.util.Collection<TimeslotISCP> value = null; 
    
            public TimeslotISCP_List () {
            }
        
            public TimeslotISCP_List ( java.util.Collection<TimeslotISCP> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<TimeslotISCP> value) {
                this.value = value;
            }
            
            public java.util.Collection<TimeslotISCP> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<TimeslotISCP>()); 
            }
            
            public void add(TimeslotISCP item) {
                value.add(item);
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TimeslotISCP_List.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            