
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "UE_RadioAccessCapabBandFDDList2" )
    public class UE_RadioAccessCapabBandFDDList2 implements IASN1PreparedElement {
                
            @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 8L 
		
	   )
	   
            @ASN1SequenceOf( name = "UE-RadioAccessCapabBandFDDList2" , isSetOf = false)
	    private java.util.Collection<UE_RadioAccessCapabBandFDD2> value = null; 
    
            public UE_RadioAccessCapabBandFDDList2 () {
            }
        
            public UE_RadioAccessCapabBandFDDList2 ( java.util.Collection<UE_RadioAccessCapabBandFDD2> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<UE_RadioAccessCapabBandFDD2> value) {
                this.value = value;
            }
            
            public java.util.Collection<UE_RadioAccessCapabBandFDD2> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<UE_RadioAccessCapabBandFDD2>()); 
            }
            
            public void add(UE_RadioAccessCapabBandFDD2 item) {
                value.add(item);
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UE_RadioAccessCapabBandFDDList2.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            