
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "UECapabilityInformation_v380ext_IEs", isSet = false )
    public class UECapabilityInformation_v380ext_IEs implements IASN1PreparedElement {
            
        @ASN1Element ( name = "ue-RadioAccessCapability-v380ext", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private UE_RadioAccessCapability_v380ext ue_RadioAccessCapability_v380ext = null;
                
  
        @ASN1Element ( name = "dl-PhysChCapabilityFDD-v380ext", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private DL_PhysChCapabilityFDD_v380ext dl_PhysChCapabilityFDD_v380ext = null;
                
  
        
        public UE_RadioAccessCapability_v380ext getUe_RadioAccessCapability_v380ext () {
            return this.ue_RadioAccessCapability_v380ext;
        }

        
        public boolean isUe_RadioAccessCapability_v380extPresent () {
            return this.ue_RadioAccessCapability_v380ext != null;
        }
        

        public void setUe_RadioAccessCapability_v380ext (UE_RadioAccessCapability_v380ext value) {
            this.ue_RadioAccessCapability_v380ext = value;
        }
        
  
        
        public DL_PhysChCapabilityFDD_v380ext getDl_PhysChCapabilityFDD_v380ext () {
            return this.dl_PhysChCapabilityFDD_v380ext;
        }

        

        public void setDl_PhysChCapabilityFDD_v380ext (DL_PhysChCapabilityFDD_v380ext value) {
            this.dl_PhysChCapabilityFDD_v380ext = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UECapabilityInformation_v380ext_IEs.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            