
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "UECapabilityInformation_v5c0ext", isSet = false )
    public class UECapabilityInformation_v5c0ext implements IASN1PreparedElement {
            
        @ASN1Element ( name = "ue-RadioAccessCapability-v5c0ext", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private UE_RadioAccessCapability_v5c0ext ue_RadioAccessCapability_v5c0ext = null;
                
  
        
        public UE_RadioAccessCapability_v5c0ext getUe_RadioAccessCapability_v5c0ext () {
            return this.ue_RadioAccessCapability_v5c0ext;
        }

        
        public boolean isUe_RadioAccessCapability_v5c0extPresent () {
            return this.ue_RadioAccessCapability_v5c0ext != null;
        }
        

        public void setUe_RadioAccessCapability_v5c0ext (UE_RadioAccessCapability_v5c0ext value) {
            this.ue_RadioAccessCapability_v5c0ext = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UECapabilityInformation_v5c0ext.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            