
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "VarianceOfRLC_BufferPayload"
    )
    public class VarianceOfRLC_BufferPayload implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "plv0", hasTag = true , tag = 0 )
            plv0 , 
            @ASN1EnumItem ( name = "plv4", hasTag = true , tag = 1 )
            plv4 , 
            @ASN1EnumItem ( name = "plv8", hasTag = true , tag = 2 )
            plv8 , 
            @ASN1EnumItem ( name = "plv16", hasTag = true , tag = 3 )
            plv16 , 
            @ASN1EnumItem ( name = "plv32", hasTag = true , tag = 4 )
            plv32 , 
            @ASN1EnumItem ( name = "plv64", hasTag = true , tag = 5 )
            plv64 , 
            @ASN1EnumItem ( name = "plv128", hasTag = true , tag = 6 )
            plv128 , 
            @ASN1EnumItem ( name = "plv256", hasTag = true , tag = 7 )
            plv256 , 
            @ASN1EnumItem ( name = "plv512", hasTag = true , tag = 8 )
            plv512 , 
            @ASN1EnumItem ( name = "plv1024", hasTag = true , tag = 9 )
            plv1024 , 
            @ASN1EnumItem ( name = "plv2k", hasTag = true , tag = 10 )
            plv2k , 
            @ASN1EnumItem ( name = "plv4k", hasTag = true , tag = 11 )
            plv4k , 
            @ASN1EnumItem ( name = "plv8k", hasTag = true , tag = 12 )
            plv8k , 
            @ASN1EnumItem ( name = "plv16k", hasTag = true , tag = 13 )
            plv16k , 
            @ASN1EnumItem ( name = "spare2", hasTag = true , tag = 14 )
            spare2 , 
            @ASN1EnumItem ( name = "spare1", hasTag = true , tag = 15 )
            spare1 , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(VarianceOfRLC_BufferPayload.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            