
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "AccessStratumReleaseIndicator"
    )
    public class AccessStratumReleaseIndicator implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "rel-4", hasTag = true , tag = 0 )
            rel_4 , 
            @ASN1EnumItem ( name = "rel-5", hasTag = true , tag = 1 )
            rel_5 , 
            @ASN1EnumItem ( name = "rel-6", hasTag = true , tag = 2 )
            rel_6 , 
            @ASN1EnumItem ( name = "spare13", hasTag = true , tag = 3 )
            spare13 , 
            @ASN1EnumItem ( name = "spare12", hasTag = true , tag = 4 )
            spare12 , 
            @ASN1EnumItem ( name = "spare11", hasTag = true , tag = 5 )
            spare11 , 
            @ASN1EnumItem ( name = "spare10", hasTag = true , tag = 6 )
            spare10 , 
            @ASN1EnumItem ( name = "spare9", hasTag = true , tag = 7 )
            spare9 , 
            @ASN1EnumItem ( name = "spare8", hasTag = true , tag = 8 )
            spare8 , 
            @ASN1EnumItem ( name = "spare7", hasTag = true , tag = 9 )
            spare7 , 
            @ASN1EnumItem ( name = "spare6", hasTag = true , tag = 10 )
            spare6 , 
            @ASN1EnumItem ( name = "spare5", hasTag = true , tag = 11 )
            spare5 , 
            @ASN1EnumItem ( name = "spare4", hasTag = true , tag = 12 )
            spare4 , 
            @ASN1EnumItem ( name = "spare3", hasTag = true , tag = 13 )
            spare3 , 
            @ASN1EnumItem ( name = "spare2", hasTag = true , tag = 14 )
            spare2 , 
            @ASN1EnumItem ( name = "spare1", hasTag = true , tag = 15 )
            spare1 , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AccessStratumReleaseIndicator.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            