
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1BitString;
import org.bn.annotations.ASN1BoxedType;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.constraints.ASN1SizeConstraint;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;
import org.bn.types.BitString;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "Ansi_41_IDNNS" )
    public class Ansi_41_IDNNS implements IASN1PreparedElement {
    
            @ASN1BitString( name = "Ansi-41-IDNNS" )
            
            @ASN1SizeConstraint ( max = 14L )
        
            private BitString value = null;
            
            public Ansi_41_IDNNS() {
            }

            public Ansi_41_IDNNS(BitString value) {
                this.value = value;
            }
            
            public void setValue(BitString value) {
                this.value = value;
            }
            
            public BitString getValue() {
                return this.value;
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Ansi_41_IDNNS.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

    }
            