
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "CellToReport", isSet = false )
    public class CellToReport implements IASN1PreparedElement {
            
        @ASN1Element ( name = "bsicReported", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private BSICReported bsicReported = null;
                
  
        
        public BSICReported getBsicReported () {
            return this.bsicReported;
        }

        

        public void setBsicReported (BSICReported value) {
            this.bsicReported = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CellToReport.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            