
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Boolean;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1Sequence;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "CompressedModeMeasCapabFDD2", isSet = false )
    public class CompressedModeMeasCapabFDD2 implements IASN1PreparedElement {
            
        @ASN1Element ( name = "radioFrequencyBandFDD", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private RadioFrequencyBandFDD radioFrequencyBandFDD = null;
                
  
        @ASN1Element ( name = "radioFrequencyBandFDD2", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private RadioFrequencyBandFDD2 radioFrequencyBandFDD2 = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "dl-MeasurementsFDD", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean dl_MeasurementsFDD = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "ul-MeasurementsFDD", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean ul_MeasurementsFDD = null;
                
  
        
        public RadioFrequencyBandFDD getRadioFrequencyBandFDD () {
            return this.radioFrequencyBandFDD;
        }

        
        public boolean isRadioFrequencyBandFDDPresent () {
            return this.radioFrequencyBandFDD != null;
        }
        

        public void setRadioFrequencyBandFDD (RadioFrequencyBandFDD value) {
            this.radioFrequencyBandFDD = value;
        }
        
  
        
        public RadioFrequencyBandFDD2 getRadioFrequencyBandFDD2 () {
            return this.radioFrequencyBandFDD2;
        }

        
        public boolean isRadioFrequencyBandFDD2Present () {
            return this.radioFrequencyBandFDD2 != null;
        }
        

        public void setRadioFrequencyBandFDD2 (RadioFrequencyBandFDD2 value) {
            this.radioFrequencyBandFDD2 = value;
        }
        
  
        
        public Boolean getDl_MeasurementsFDD () {
            return this.dl_MeasurementsFDD;
        }

        

        public void setDl_MeasurementsFDD (Boolean value) {
            this.dl_MeasurementsFDD = value;
        }
        
  
        
        public Boolean getUl_MeasurementsFDD () {
            return this.ul_MeasurementsFDD;
        }

        

        public void setUl_MeasurementsFDD (Boolean value) {
            this.ul_MeasurementsFDD = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CompressedModeMeasCapabFDD2.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            