
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Boolean;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1Sequence;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "CompressedModeMeasCapabMC", isSet = false )
    public class CompressedModeMeasCapabMC implements IASN1PreparedElement {
            @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "dl-MeasurementsMC", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean dl_MeasurementsMC = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "ul-MeasurementsMC", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean ul_MeasurementsMC = null;
                
  
        
        public Boolean getDl_MeasurementsMC () {
            return this.dl_MeasurementsMC;
        }

        

        public void setDl_MeasurementsMC (Boolean value) {
            this.dl_MeasurementsMC = value;
        }
        
  
        
        public Boolean getUl_MeasurementsMC () {
            return this.ul_MeasurementsMC;
        }

        

        public void setUl_MeasurementsMC (Boolean value) {
            this.ul_MeasurementsMC = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CompressedModeMeasCapabMC.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            