
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "CompressedModeMeasCapabGSM", isSet = false )
    public class CompressedModeMeasCapabGSM implements IASN1PreparedElement {
            
        @ASN1Element ( name = "radioFrequencyBandGSM", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RadioFrequencyBandGSM radioFrequencyBandGSM = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "dl-MeasurementsGSM", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean dl_MeasurementsGSM = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "ul-MeasurementsGSM", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean ul_MeasurementsGSM = null;
                
  
        
        public RadioFrequencyBandGSM getRadioFrequencyBandGSM () {
            return this.radioFrequencyBandGSM;
        }

        

        public void setRadioFrequencyBandGSM (RadioFrequencyBandGSM value) {
            this.radioFrequencyBandGSM = value;
        }
        
  
        
        public Boolean getDl_MeasurementsGSM () {
            return this.dl_MeasurementsGSM;
        }

        

        public void setDl_MeasurementsGSM (Boolean value) {
            this.dl_MeasurementsGSM = value;
        }
        
  
        
        public Boolean getUl_MeasurementsGSM () {
            return this.ul_MeasurementsGSM;
        }

        

        public void setUl_MeasurementsGSM (Boolean value) {
            this.ul_MeasurementsGSM = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CompressedModeMeasCapabGSM.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            