
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "CompressedModeMeasCapability", isSet = false )
    public class CompressedModeMeasCapability implements IASN1PreparedElement {
            @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "fdd-Measurements", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean fdd_Measurements = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "tdd-Measurements", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean tdd_Measurements = null;
                
  
        @ASN1Element ( name = "gsm-Measurements", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private GSM_Measurements gsm_Measurements = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "multiCarrierMeasurements", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private Boolean multiCarrierMeasurements = null;
                
  
        
        public Boolean getFdd_Measurements () {
            return this.fdd_Measurements;
        }

        

        public void setFdd_Measurements (Boolean value) {
            this.fdd_Measurements = value;
        }
        
  
        
        public Boolean getTdd_Measurements () {
            return this.tdd_Measurements;
        }

        
        public boolean isTdd_MeasurementsPresent () {
            return this.tdd_Measurements != null;
        }
        

        public void setTdd_Measurements (Boolean value) {
            this.tdd_Measurements = value;
        }
        
  
        
        public GSM_Measurements getGsm_Measurements () {
            return this.gsm_Measurements;
        }

        
        public boolean isGsm_MeasurementsPresent () {
            return this.gsm_Measurements != null;
        }
        

        public void setGsm_Measurements (GSM_Measurements value) {
            this.gsm_Measurements = value;
        }
        
  
        
        public Boolean getMultiCarrierMeasurements () {
            return this.multiCarrierMeasurements;
        }

        
        public boolean isMultiCarrierMeasurementsPresent () {
            return this.multiCarrierMeasurements != null;
        }
        

        public void setMultiCarrierMeasurements (Boolean value) {
            this.multiCarrierMeasurements = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CompressedModeMeasCapability.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            