
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "DL_CapabilityWithSimultaneousHS_DSCHConfig"
    )
    public class DL_CapabilityWithSimultaneousHS_DSCHConfig implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "kbps32", hasTag = true , tag = 0 )
            kbps32 , 
            @ASN1EnumItem ( name = "kbps64", hasTag = true , tag = 1 )
            kbps64 , 
            @ASN1EnumItem ( name = "kbps128", hasTag = true , tag = 2 )
            kbps128 , 
            @ASN1EnumItem ( name = "kbps384", hasTag = true , tag = 3 )
            kbps384 , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DL_CapabilityWithSimultaneousHS_DSCHConfig.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            