
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "DL_PhysChCapabilityFDD_v380ext", isSet = false )
    public class DL_PhysChCapabilityFDD_v380ext implements IASN1PreparedElement {
            
        @ASN1Element ( name = "dummy", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private SupportOfDedicatedPilotsForChEstimation dummy = null;
                
  
        
        public SupportOfDedicatedPilotsForChEstimation getDummy () {
            return this.dummy;
        }

        
        public boolean isDummyPresent () {
            return this.dummy != null;
        }
        

        public void setDummy (SupportOfDedicatedPilotsForChEstimation value) {
            this.dummy = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DL_PhysChCapabilityFDD_v380ext.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            