
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "DL_TransChCapability", isSet = false )
    public class DL_TransChCapability implements IASN1PreparedElement {
            
        @ASN1Element ( name = "maxNoBitsReceived", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MaxNoBits maxNoBitsReceived = null;
                
  
        @ASN1Element ( name = "maxConvCodeBitsReceived", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MaxNoBits maxConvCodeBitsReceived = null;
                
  
        @ASN1Element ( name = "turboDecodingSupport", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private TurboSupport turboDecodingSupport = null;
                
  
        @ASN1Element ( name = "maxSimultaneousTransChs", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MaxSimultaneousTransChsDL maxSimultaneousTransChs = null;
                
  
        @ASN1Element ( name = "maxSimultaneousCCTrCH-Count", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MaxSimultaneousCCTrCH_Count maxSimultaneousCCTrCH_Count = null;
                
  
        @ASN1Element ( name = "maxReceivedTransportBlocks", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MaxTransportBlocksDL maxReceivedTransportBlocks = null;
                
  
        @ASN1Element ( name = "maxNumberOfTFC", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MaxNumberOfTFC_DL maxNumberOfTFC = null;
                
  
        @ASN1Element ( name = "maxNumberOfTF", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MaxNumberOfTF maxNumberOfTF = null;
                
  
        
        public MaxNoBits getMaxNoBitsReceived () {
            return this.maxNoBitsReceived;
        }

        

        public void setMaxNoBitsReceived (MaxNoBits value) {
            this.maxNoBitsReceived = value;
        }
        
  
        
        public MaxNoBits getMaxConvCodeBitsReceived () {
            return this.maxConvCodeBitsReceived;
        }

        

        public void setMaxConvCodeBitsReceived (MaxNoBits value) {
            this.maxConvCodeBitsReceived = value;
        }
        
  
        
        public TurboSupport getTurboDecodingSupport () {
            return this.turboDecodingSupport;
        }

        

        public void setTurboDecodingSupport (TurboSupport value) {
            this.turboDecodingSupport = value;
        }
        
  
        
        public MaxSimultaneousTransChsDL getMaxSimultaneousTransChs () {
            return this.maxSimultaneousTransChs;
        }

        

        public void setMaxSimultaneousTransChs (MaxSimultaneousTransChsDL value) {
            this.maxSimultaneousTransChs = value;
        }
        
  
        
        public MaxSimultaneousCCTrCH_Count getMaxSimultaneousCCTrCH_Count () {
            return this.maxSimultaneousCCTrCH_Count;
        }

        

        public void setMaxSimultaneousCCTrCH_Count (MaxSimultaneousCCTrCH_Count value) {
            this.maxSimultaneousCCTrCH_Count = value;
        }
        
  
        
        public MaxTransportBlocksDL getMaxReceivedTransportBlocks () {
            return this.maxReceivedTransportBlocks;
        }

        

        public void setMaxReceivedTransportBlocks (MaxTransportBlocksDL value) {
            this.maxReceivedTransportBlocks = value;
        }
        
  
        
        public MaxNumberOfTFC_DL getMaxNumberOfTFC () {
            return this.maxNumberOfTFC;
        }

        

        public void setMaxNumberOfTFC (MaxNumberOfTFC_DL value) {
            this.maxNumberOfTFC = value;
        }
        
  
        
        public MaxNumberOfTF getMaxNumberOfTF () {
            return this.maxNumberOfTF;
        }

        

        public void setMaxNumberOfTF (MaxNumberOfTF value) {
            this.maxNumberOfTF = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DL_TransChCapability.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            