
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "EventResults" )
    public class EventResults implements IASN1PreparedElement {
            
        @ASN1Element ( name = "intraFreqEventResults", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private IntraFreqEventResults intraFreqEventResults = null;
                
  
        @ASN1Element ( name = "interFreqEventResults", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private InterFreqEventResults interFreqEventResults = null;
                
  
        @ASN1Element ( name = "interRATEventResults", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private InterRATEventResults interRATEventResults = null;
                
  
        @ASN1Element ( name = "trafficVolumeEventResults", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private TrafficVolumeEventResults trafficVolumeEventResults = null;
                
  
        @ASN1Element ( name = "qualityEventResults", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private QualityEventResults qualityEventResults = null;
                
  
        @ASN1Element ( name = "ue-InternalEventResults", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UE_InternalEventResults ue_InternalEventResults = null;
                
  
        @ASN1Element ( name = "ue-positioning-MeasurementEventResults", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UE_Positioning_MeasurementEventResults ue_positioning_MeasurementEventResults = null;
                
  
        @ASN1Null ( name = "spare" ) 
    
        @ASN1Element ( name = "spare", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject spare = null;
                
  
        
        public IntraFreqEventResults getIntraFreqEventResults () {
            return this.intraFreqEventResults;
        }

        public boolean isIntraFreqEventResultsSelected () {
            return this.intraFreqEventResults != null;
        }

        private void setIntraFreqEventResults (IntraFreqEventResults value) {
            this.intraFreqEventResults = value;
        }

        
        public void selectIntraFreqEventResults (IntraFreqEventResults value) {
            this.intraFreqEventResults = value;
            
                    setInterFreqEventResults(null);
                
                    setInterRATEventResults(null);
                
                    setTrafficVolumeEventResults(null);
                
                    setQualityEventResults(null);
                
                    setUe_InternalEventResults(null);
                
                    setUe_positioning_MeasurementEventResults(null);
                
                    setSpare(null);
                            
        }

        
  
        
        public InterFreqEventResults getInterFreqEventResults () {
            return this.interFreqEventResults;
        }

        public boolean isInterFreqEventResultsSelected () {
            return this.interFreqEventResults != null;
        }

        private void setInterFreqEventResults (InterFreqEventResults value) {
            this.interFreqEventResults = value;
        }

        
        public void selectInterFreqEventResults (InterFreqEventResults value) {
            this.interFreqEventResults = value;
            
                    setIntraFreqEventResults(null);
                
                    setInterRATEventResults(null);
                
                    setTrafficVolumeEventResults(null);
                
                    setQualityEventResults(null);
                
                    setUe_InternalEventResults(null);
                
                    setUe_positioning_MeasurementEventResults(null);
                
                    setSpare(null);
                            
        }

        
  
        
        public InterRATEventResults getInterRATEventResults () {
            return this.interRATEventResults;
        }

        public boolean isInterRATEventResultsSelected () {
            return this.interRATEventResults != null;
        }

        private void setInterRATEventResults (InterRATEventResults value) {
            this.interRATEventResults = value;
        }

        
        public void selectInterRATEventResults (InterRATEventResults value) {
            this.interRATEventResults = value;
            
                    setIntraFreqEventResults(null);
                
                    setInterFreqEventResults(null);
                
                    setTrafficVolumeEventResults(null);
                
                    setQualityEventResults(null);
                
                    setUe_InternalEventResults(null);
                
                    setUe_positioning_MeasurementEventResults(null);
                
                    setSpare(null);
                            
        }

        
  
        
        public TrafficVolumeEventResults getTrafficVolumeEventResults () {
            return this.trafficVolumeEventResults;
        }

        public boolean isTrafficVolumeEventResultsSelected () {
            return this.trafficVolumeEventResults != null;
        }

        private void setTrafficVolumeEventResults (TrafficVolumeEventResults value) {
            this.trafficVolumeEventResults = value;
        }

        
        public void selectTrafficVolumeEventResults (TrafficVolumeEventResults value) {
            this.trafficVolumeEventResults = value;
            
                    setIntraFreqEventResults(null);
                
                    setInterFreqEventResults(null);
                
                    setInterRATEventResults(null);
                
                    setQualityEventResults(null);
                
                    setUe_InternalEventResults(null);
                
                    setUe_positioning_MeasurementEventResults(null);
                
                    setSpare(null);
                            
        }

        
  
        
        public QualityEventResults getQualityEventResults () {
            return this.qualityEventResults;
        }

        public boolean isQualityEventResultsSelected () {
            return this.qualityEventResults != null;
        }

        private void setQualityEventResults (QualityEventResults value) {
            this.qualityEventResults = value;
        }

        
        public void selectQualityEventResults (QualityEventResults value) {
            this.qualityEventResults = value;
            
                    setIntraFreqEventResults(null);
                
                    setInterFreqEventResults(null);
                
                    setInterRATEventResults(null);
                
                    setTrafficVolumeEventResults(null);
                
                    setUe_InternalEventResults(null);
                
                    setUe_positioning_MeasurementEventResults(null);
                
                    setSpare(null);
                            
        }

        
  
        
        public UE_InternalEventResults getUe_InternalEventResults () {
            return this.ue_InternalEventResults;
        }

        public boolean isUe_InternalEventResultsSelected () {
            return this.ue_InternalEventResults != null;
        }

        private void setUe_InternalEventResults (UE_InternalEventResults value) {
            this.ue_InternalEventResults = value;
        }

        
        public void selectUe_InternalEventResults (UE_InternalEventResults value) {
            this.ue_InternalEventResults = value;
            
                    setIntraFreqEventResults(null);
                
                    setInterFreqEventResults(null);
                
                    setInterRATEventResults(null);
                
                    setTrafficVolumeEventResults(null);
                
                    setQualityEventResults(null);
                
                    setUe_InternalEventResults(null);
                
                    setUe_positioning_MeasurementEventResults(null);
                
                    setSpare(null);
                            
        }

        
  
        
        public UE_Positioning_MeasurementEventResults getUe_positioning_MeasurementEventResults () {
            return this.ue_positioning_MeasurementEventResults;
        }

        public boolean isUe_positioning_MeasurementEventResultsSelected () {
            return this.ue_positioning_MeasurementEventResults != null;
        }

        private void setUe_positioning_MeasurementEventResults (UE_Positioning_MeasurementEventResults value) {
            this.ue_positioning_MeasurementEventResults = value;
        }

        
        public void selectUe_positioning_MeasurementEventResults (UE_Positioning_MeasurementEventResults value) {
            this.ue_positioning_MeasurementEventResults = value;
            
                    setIntraFreqEventResults(null);
                
                    setInterFreqEventResults(null);
                
                    setInterRATEventResults(null);
                
                    setTrafficVolumeEventResults(null);
                
                    setQualityEventResults(null);
                
                    setUe_InternalEventResults(null);
                
                    setUe_positioning_MeasurementEventResults(null);
                
                    setSpare(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getSpare () {
            return this.spare;
        }

        public boolean isSpareSelected () {
            return this.spare != null;
        }

        private void setSpare (org.bn.types.NullObject value) {
            this.spare = value;
        }

        
        public void selectSpare () {
            selectSpare (new org.bn.types.NullObject());
	}
	
        public void selectSpare (org.bn.types.NullObject value) {
            this.spare = value;
            
                    setIntraFreqEventResults(null);
                
                    setInterFreqEventResults(null);
                
                    setInterRATEventResults(null);
                
                    setTrafficVolumeEventResults(null);
                
                    setQualityEventResults(null);
                
                    setUe_InternalEventResults(null);
                
                    setUe_positioning_MeasurementEventResults(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(EventResults.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            