
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1Sequence;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "FrequencyInfoTDD", isSet = false )
    public class FrequencyInfoTDD implements IASN1PreparedElement {
            
        @ASN1Element ( name = "uarfcn-Nt", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UARFCN uarfcn_Nt = null;
                
  
        
        public UARFCN getUarfcn_Nt () {
            return this.uarfcn_Nt;
        }

        

        public void setUarfcn_Nt (UARFCN value) {
            this.uarfcn_Nt = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(FrequencyInfoTDD.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            