
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "GSM_MeasuredResults", isSet = false )
    public class GSM_MeasuredResults implements IASN1PreparedElement {
            
        @ASN1Element ( name = "gsm-CarrierRSSI", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private GSM_CarrierRSSI gsm_CarrierRSSI = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 46L, 
		
		max = 173L 
		
	   )
	   
        @ASN1Element ( name = "dummy", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer dummy = null;
                
  
        @ASN1Element ( name = "bsicReported", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private BSICReported bsicReported = null;
                
  
        @ASN1Element ( name = "dummy2", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ObservedTimeDifferenceToGSM dummy2 = null;
                
  
        
        public GSM_CarrierRSSI getGsm_CarrierRSSI () {
            return this.gsm_CarrierRSSI;
        }

        
        public boolean isGsm_CarrierRSSIPresent () {
            return this.gsm_CarrierRSSI != null;
        }
        

        public void setGsm_CarrierRSSI (GSM_CarrierRSSI value) {
            this.gsm_CarrierRSSI = value;
        }
        
  
        
        public Integer getDummy () {
            return this.dummy;
        }

        
        public boolean isDummyPresent () {
            return this.dummy != null;
        }
        

        public void setDummy (Integer value) {
            this.dummy = value;
        }
        
  
        
        public BSICReported getBsicReported () {
            return this.bsicReported;
        }

        

        public void setBsicReported (BSICReported value) {
            this.bsicReported = value;
        }
        
  
        
        public ObservedTimeDifferenceToGSM getDummy2 () {
            return this.dummy2;
        }

        
        public boolean isDummy2Present () {
            return this.dummy2 != null;
        }
        

        public void setDummy2 (ObservedTimeDifferenceToGSM value) {
            this.dummy2 = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(GSM_MeasuredResults.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            