
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1Sequence;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "InitialDirectTransfer_v590ext", isSet = false )
    public class InitialDirectTransfer_v590ext implements IASN1PreparedElement {
            
        @ASN1Element ( name = "establishmentCause", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private EstablishmentCause establishmentCause = null;
                
  
        
        public EstablishmentCause getEstablishmentCause () {
            return this.establishmentCause;
        }

        
        public boolean isEstablishmentCausePresent () {
            return this.establishmentCause != null;
        }
        

        public void setEstablishmentCause (EstablishmentCause value) {
            this.establishmentCause = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(InitialDirectTransfer_v590ext.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            