
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "InitialDirectTransfer_v3a0ext", isSet = false )
    public class InitialDirectTransfer_v3a0ext implements IASN1PreparedElement {
            
        @ASN1Element ( name = "start-Value", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private START_Value start_Value = null;
                
  
        
        public START_Value getStart_Value () {
            return this.start_Value;
        }

        
        public boolean isStart_ValuePresent () {
            return this.start_Value != null;
        }
        

        public void setStart_Value (START_Value value) {
            this.start_Value = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(InitialDirectTransfer_v3a0ext.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            