
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "IntegrityCheckInfo", isSet = false )
    public class IntegrityCheckInfo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "messageAuthenticationCode", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MessageAuthenticationCode messageAuthenticationCode = null;
                
  
        @ASN1Element ( name = "rrc-MessageSequenceNumber", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RRC_MessageSequenceNumber rrc_MessageSequenceNumber = null;
                
  
        
        public MessageAuthenticationCode getMessageAuthenticationCode () {
            return this.messageAuthenticationCode;
        }

        

        public void setMessageAuthenticationCode (MessageAuthenticationCode value) {
            this.messageAuthenticationCode = value;
        }
        
  
        
        public RRC_MessageSequenceNumber getRrc_MessageSequenceNumber () {
            return this.rrc_MessageSequenceNumber;
        }

        

        public void setRrc_MessageSequenceNumber (RRC_MessageSequenceNumber value) {
            this.rrc_MessageSequenceNumber = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(IntegrityCheckInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            