
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "IntraFreqEventResults", isSet = false )
    public class IntraFreqEventResults implements IASN1PreparedElement {
            
        @ASN1Element ( name = "eventID", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private EventIDIntraFreq eventID = null;
                
  
        @ASN1Element ( name = "cellMeasurementEventResults", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private CellMeasurementEventResults cellMeasurementEventResults = null;
                
  
        
        public EventIDIntraFreq getEventID () {
            return this.eventID;
        }

        

        public void setEventID (EventIDIntraFreq value) {
            this.eventID = value;
        }
        
  
        
        public CellMeasurementEventResults getCellMeasurementEventResults () {
            return this.cellMeasurementEventResults;
        }

        

        public void setCellMeasurementEventResults (CellMeasurementEventResults value) {
            this.cellMeasurementEventResults = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(IntraFreqEventResults.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            