
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "MaxHcContextSpace"
    )
    public class MaxHcContextSpace implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "dummy", hasTag = true , tag = 0 )
            dummy , 
            @ASN1EnumItem ( name = "by1024", hasTag = true , tag = 1 )
            by1024 , 
            @ASN1EnumItem ( name = "by2048", hasTag = true , tag = 2 )
            by2048 , 
            @ASN1EnumItem ( name = "by4096", hasTag = true , tag = 3 )
            by4096 , 
            @ASN1EnumItem ( name = "by8192", hasTag = true , tag = 4 )
            by8192 , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MaxHcContextSpace.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            