
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "MaxPhysChPerSubFrame_r4" )
    public class MaxPhysChPerSubFrame_r4 implements IASN1PreparedElement {
    
            @ASN1Integer( name = "MaxPhysChPerSubFrame-r4" )
            @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 96L 
		
	   )
	   
            private Integer value;
            
            public MaxPhysChPerSubFrame_r4() {
            }

            public MaxPhysChPerSubFrame_r4(Integer value) {
                this.value = value;
            }
            
            public void setValue(Integer value) {
                this.value = value;
            }
            
            public Integer getValue() {
                return this.value;
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MaxPhysChPerSubFrame_r4.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            