
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "MBMS_JoinedInformation_r6", isSet = false )
    public class MBMS_JoinedInformation_r6 implements IASN1PreparedElement {
            
        @ASN1Element ( name = "p-TMSI", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private P_TMSI_GSM_MAP p_TMSI = null;
                
  
        
        public P_TMSI_GSM_MAP getP_TMSI () {
            return this.p_TMSI;
        }

        
        public boolean isP_TMSIPresent () {
            return this.p_TMSI != null;
        }
        

        public void setP_TMSI (P_TMSI_GSM_MAP value) {
            this.p_TMSI = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MBMS_JoinedInformation_r6.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            