
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "MeasurementControlFailure_v590ext_IEs", isSet = false )
    public class MeasurementControlFailure_v590ext_IEs implements IASN1PreparedElement {
            
        @ASN1Element ( name = "rrc-TransactionIdentifier-MSP-v590ext", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RRC_TransactionIdentifier rrc_TransactionIdentifier_MSP_v590ext = null;
                
  
        
        public RRC_TransactionIdentifier getRrc_TransactionIdentifier_MSP_v590ext () {
            return this.rrc_TransactionIdentifier_MSP_v590ext;
        }

        

        public void setRrc_TransactionIdentifier_MSP_v590ext (RRC_TransactionIdentifier value) {
            this.rrc_TransactionIdentifier_MSP_v590ext = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MeasurementControlFailure_v590ext_IEs.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            