
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1Sequence;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "MeasurementCapability", isSet = false )
    public class MeasurementCapability implements IASN1PreparedElement {
            
        @ASN1Element ( name = "downlinkCompressedMode", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private CompressedModeMeasCapability downlinkCompressedMode = null;
                
  
        @ASN1Element ( name = "uplinkCompressedMode", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private CompressedModeMeasCapability uplinkCompressedMode = null;
                
  
        
        public CompressedModeMeasCapability getDownlinkCompressedMode () {
            return this.downlinkCompressedMode;
        }

        

        public void setDownlinkCompressedMode (CompressedModeMeasCapability value) {
            this.downlinkCompressedMode = value;
        }
        
  
        
        public CompressedModeMeasCapability getUplinkCompressedMode () {
            return this.uplinkCompressedMode;
        }

        

        public void setUplinkCompressedMode (CompressedModeMeasCapability value) {
            this.uplinkCompressedMode = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MeasurementCapability.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            