
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "NAS_Message" )
    public class NAS_Message implements IASN1PreparedElement {
    
            @ASN1OctetString( name = "NAS-Message" )
            @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 4095L 
		
	   )
	   
            private byte[] value = null;
            
            public NAS_Message() {
            }

            public NAS_Message(byte[] value) {
                this.value = value;
            }

            public NAS_Message(BitString value) {
                setValue(value);
            }
            
            public void setValue(byte[] value) {
                this.value = value;
            }

            public void setValue(BitString btStr) {
                this.value = btStr.getValue();
            }
            
            public byte[] getValue() {
                return this.value;
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(NAS_Message.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            