
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "NetworkAssistedGPS_Supported"
    )
    public class NetworkAssistedGPS_Supported implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "networkBased", hasTag = true , tag = 0 )
            networkBased , 
            @ASN1EnumItem ( name = "ue-Based", hasTag = true , tag = 1 )
            ue_Based , 
            @ASN1EnumItem ( name = "bothNetworkAndUE-Based", hasTag = true , tag = 2 )
            bothNetworkAndUE_Based , 
            @ASN1EnumItem ( name = "noNetworkAssistedGPS", hasTag = true , tag = 3 )
            noNetworkAssistedGPS , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(NetworkAssistedGPS_Supported.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            