
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1Enum;
import org.bn.annotations.ASN1EnumItem;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1Sequence;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PDCP_Capability_r5_ext2", isSet = false )
    public class PDCP_Capability_r5_ext2 implements IASN1PreparedElement {
            

    @ASN1PreparedElement
    @ASN1Enum (
        name = "LosslessDLRLC-PDUSizeChangeEnumType"
    )
    public static class LosslessDLRLC_PDUSizeChangeEnumType implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "true", hasTag = true , tag = 0 )
            TRUE , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(LosslessDLRLC_PDUSizeChangeEnumType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

    }
                
        @ASN1Element ( name = "losslessDLRLC-PDUSizeChange", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private LosslessDLRLC_PDUSizeChangeEnumType losslessDLRLC_PDUSizeChange = null;
                
  
        
        public LosslessDLRLC_PDUSizeChangeEnumType getLosslessDLRLC_PDUSizeChange () {
            return this.losslessDLRLC_PDUSizeChange;
        }

        
        public boolean isLosslessDLRLC_PDUSizeChangePresent () {
            return this.losslessDLRLC_PDUSizeChange != null;
        }
        

        public void setLosslessDLRLC_PDUSizeChange (LosslessDLRLC_PDUSizeChangeEnumType value) {
            this.losslessDLRLC_PDUSizeChange = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PDCP_Capability_r5_ext2.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            