
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PLMN_Identity", isSet = false )
    public class PLMN_Identity implements IASN1PreparedElement {
            
        @ASN1Element ( name = "mcc", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MCC mcc = null;
                
  
        @ASN1Element ( name = "mnc", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MNC mnc = null;
                
  
        
        public MCC getMcc () {
            return this.mcc;
        }

        

        public void setMcc (MCC value) {
            this.mcc = value;
        }
        
  
        
        public MNC getMnc () {
            return this.mnc;
        }

        

        public void setMnc (MNC value) {
            this.mnc = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PLMN_Identity.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            