
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "PositionEstimate" )
    public class PositionEstimate implements IASN1PreparedElement {
            
        @ASN1Element ( name = "ellipsoidPoint", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private EllipsoidPoint ellipsoidPoint = null;
                
  
        @ASN1Element ( name = "ellipsoidPointUncertCircle", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private EllipsoidPointUncertCircle ellipsoidPointUncertCircle = null;
                
  
        @ASN1Element ( name = "ellipsoidPointUncertEllipse", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private EllipsoidPointUncertEllipse ellipsoidPointUncertEllipse = null;
                
  
        @ASN1Element ( name = "ellipsoidPointAltitude", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private EllipsoidPointAltitude ellipsoidPointAltitude = null;
                
  
        @ASN1Element ( name = "ellipsoidPointAltitudeEllipse", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private EllipsoidPointAltitudeEllipsoide ellipsoidPointAltitudeEllipse = null;
                
  
        
        public EllipsoidPoint getEllipsoidPoint () {
            return this.ellipsoidPoint;
        }

        public boolean isEllipsoidPointSelected () {
            return this.ellipsoidPoint != null;
        }

        private void setEllipsoidPoint (EllipsoidPoint value) {
            this.ellipsoidPoint = value;
        }

        
        public void selectEllipsoidPoint (EllipsoidPoint value) {
            this.ellipsoidPoint = value;
            
                    setEllipsoidPointUncertCircle(null);
                
                    setEllipsoidPointUncertEllipse(null);
                
                    setEllipsoidPointAltitude(null);
                
                    setEllipsoidPointAltitudeEllipse(null);
                            
        }

        
  
        
        public EllipsoidPointUncertCircle getEllipsoidPointUncertCircle () {
            return this.ellipsoidPointUncertCircle;
        }

        public boolean isEllipsoidPointUncertCircleSelected () {
            return this.ellipsoidPointUncertCircle != null;
        }

        private void setEllipsoidPointUncertCircle (EllipsoidPointUncertCircle value) {
            this.ellipsoidPointUncertCircle = value;
        }

        
        public void selectEllipsoidPointUncertCircle (EllipsoidPointUncertCircle value) {
            this.ellipsoidPointUncertCircle = value;
            
                    setEllipsoidPoint(null);
                
                    setEllipsoidPointUncertEllipse(null);
                
                    setEllipsoidPointAltitude(null);
                
                    setEllipsoidPointAltitudeEllipse(null);
                            
        }

        
  
        
        public EllipsoidPointUncertEllipse getEllipsoidPointUncertEllipse () {
            return this.ellipsoidPointUncertEllipse;
        }

        public boolean isEllipsoidPointUncertEllipseSelected () {
            return this.ellipsoidPointUncertEllipse != null;
        }

        private void setEllipsoidPointUncertEllipse (EllipsoidPointUncertEllipse value) {
            this.ellipsoidPointUncertEllipse = value;
        }

        
        public void selectEllipsoidPointUncertEllipse (EllipsoidPointUncertEllipse value) {
            this.ellipsoidPointUncertEllipse = value;
            
                    setEllipsoidPoint(null);
                
                    setEllipsoidPointUncertCircle(null);
                
                    setEllipsoidPointAltitude(null);
                
                    setEllipsoidPointAltitudeEllipse(null);
                            
        }

        
  
        
        public EllipsoidPointAltitude getEllipsoidPointAltitude () {
            return this.ellipsoidPointAltitude;
        }

        public boolean isEllipsoidPointAltitudeSelected () {
            return this.ellipsoidPointAltitude != null;
        }

        private void setEllipsoidPointAltitude (EllipsoidPointAltitude value) {
            this.ellipsoidPointAltitude = value;
        }

        
        public void selectEllipsoidPointAltitude (EllipsoidPointAltitude value) {
            this.ellipsoidPointAltitude = value;
            
                    setEllipsoidPoint(null);
                
                    setEllipsoidPointUncertCircle(null);
                
                    setEllipsoidPointUncertEllipse(null);
                
                    setEllipsoidPointAltitudeEllipse(null);
                            
        }

        
  
        
        public EllipsoidPointAltitudeEllipsoide getEllipsoidPointAltitudeEllipse () {
            return this.ellipsoidPointAltitudeEllipse;
        }

        public boolean isEllipsoidPointAltitudeEllipseSelected () {
            return this.ellipsoidPointAltitudeEllipse != null;
        }

        private void setEllipsoidPointAltitudeEllipse (EllipsoidPointAltitudeEllipsoide value) {
            this.ellipsoidPointAltitudeEllipse = value;
        }

        
        public void selectEllipsoidPointAltitudeEllipse (EllipsoidPointAltitudeEllipsoide value) {
            this.ellipsoidPointAltitudeEllipse = value;
            
                    setEllipsoidPoint(null);
                
                    setEllipsoidPointUncertCircle(null);
                
                    setEllipsoidPointUncertEllipse(null);
                
                    setEllipsoidPointAltitude(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PositionEstimate.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            