
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Enum;
import org.bn.annotations.ASN1EnumItem;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "ProtocolErrorCause"
    )
    public class ProtocolErrorCause implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "asn1-ViolationOrEncodingError", hasTag = true , tag = 0 )
            asn1_ViolationOrEncodingError , 
            @ASN1EnumItem ( name = "messageTypeNonexistent", hasTag = true , tag = 1 )
            messageTypeNonexistent , 
            @ASN1EnumItem ( name = "messageNotCompatibleWithReceiverState", hasTag = true , tag = 2 )
            messageNotCompatibleWithReceiverState , 
            @ASN1EnumItem ( name = "ie-ValueNotComprehended", hasTag = true , tag = 3 )
            ie_ValueNotComprehended , 
            @ASN1EnumItem ( name = "informationElementMissing", hasTag = true , tag = 4 )
            informationElementMissing , 
            @ASN1EnumItem ( name = "messageExtensionNotComprehended", hasTag = true , tag = 5 )
            messageExtensionNotComprehended , 
            @ASN1EnumItem ( name = "spare2", hasTag = true , tag = 6 )
            spare2 , 
            @ASN1EnumItem ( name = "spare1", hasTag = true , tag = 7 )
            spare1 , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ProtocolErrorCause.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            