
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "RadioFrequencyBandTDDList"
    )
    public class RadioFrequencyBandTDDList implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "a", hasTag = true , tag = 0 )
            a , 
            @ASN1EnumItem ( name = "b", hasTag = true , tag = 1 )
            b , 
            @ASN1EnumItem ( name = "c", hasTag = true , tag = 2 )
            c , 
            @ASN1EnumItem ( name = "ab", hasTag = true , tag = 3 )
            ab , 
            @ASN1EnumItem ( name = "ac", hasTag = true , tag = 4 )
            ac , 
            @ASN1EnumItem ( name = "bc", hasTag = true , tag = 5 )
            bc , 
            @ASN1EnumItem ( name = "abc", hasTag = true , tag = 6 )
            abc , 
            @ASN1EnumItem ( name = "spare", hasTag = true , tag = 7 )
            spare , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RadioFrequencyBandTDDList.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            