
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1Sequence;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "RB_ActivationTimeInfo", isSet = false )
    public class RB_ActivationTimeInfo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "rb-Identity", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RB_Identity rb_Identity = null;
                
  
        @ASN1Element ( name = "rlc-SequenceNumber", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private RLC_SequenceNumber rlc_SequenceNumber = null;
                
  
        
        public RB_Identity getRb_Identity () {
            return this.rb_Identity;
        }

        

        public void setRb_Identity (RB_Identity value) {
            this.rb_Identity = value;
        }
        
  
        
        public RLC_SequenceNumber getRlc_SequenceNumber () {
            return this.rlc_SequenceNumber;
        }

        

        public void setRlc_SequenceNumber (RLC_SequenceNumber value) {
            this.rlc_SequenceNumber = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RB_ActivationTimeInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            