
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "RB_WithPDCP_InfoList" )
    public class RB_WithPDCP_InfoList implements IASN1PreparedElement {
                
            @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 27L 
		
	   )
	   
            @ASN1SequenceOf( name = "RB-WithPDCP-InfoList" , isSetOf = false)
	    private java.util.Collection<RB_WithPDCP_Info> value = null; 
    
            public RB_WithPDCP_InfoList () {
            }
        
            public RB_WithPDCP_InfoList ( java.util.Collection<RB_WithPDCP_Info> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<RB_WithPDCP_Info> value) {
                this.value = value;
            }
            
            public java.util.Collection<RB_WithPDCP_Info> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<RB_WithPDCP_Info>()); 
            }
            
            public void add(RB_WithPDCP_Info item) {
                value.add(item);
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RB_WithPDCP_InfoList.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            