
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "RLC_BuffersPayload"
    )
    public class RLC_BuffersPayload implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "pl0", hasTag = true , tag = 0 )
            pl0 , 
            @ASN1EnumItem ( name = "pl4", hasTag = true , tag = 1 )
            pl4 , 
            @ASN1EnumItem ( name = "pl8", hasTag = true , tag = 2 )
            pl8 , 
            @ASN1EnumItem ( name = "pl16", hasTag = true , tag = 3 )
            pl16 , 
            @ASN1EnumItem ( name = "pl32", hasTag = true , tag = 4 )
            pl32 , 
            @ASN1EnumItem ( name = "pl64", hasTag = true , tag = 5 )
            pl64 , 
            @ASN1EnumItem ( name = "pl128", hasTag = true , tag = 6 )
            pl128 , 
            @ASN1EnumItem ( name = "pl256", hasTag = true , tag = 7 )
            pl256 , 
            @ASN1EnumItem ( name = "pl512", hasTag = true , tag = 8 )
            pl512 , 
            @ASN1EnumItem ( name = "pl1024", hasTag = true , tag = 9 )
            pl1024 , 
            @ASN1EnumItem ( name = "pl2k", hasTag = true , tag = 10 )
            pl2k , 
            @ASN1EnumItem ( name = "pl4k", hasTag = true , tag = 11 )
            pl4k , 
            @ASN1EnumItem ( name = "pl8k", hasTag = true , tag = 12 )
            pl8k , 
            @ASN1EnumItem ( name = "pl16k", hasTag = true , tag = 13 )
            pl16k , 
            @ASN1EnumItem ( name = "pl32k", hasTag = true , tag = 14 )
            pl32k , 
            @ASN1EnumItem ( name = "pl64k", hasTag = true , tag = 15 )
            pl64k , 
            @ASN1EnumItem ( name = "pl128k", hasTag = true , tag = 16 )
            pl128k , 
            @ASN1EnumItem ( name = "pl256k", hasTag = true , tag = 17 )
            pl256k , 
            @ASN1EnumItem ( name = "pl512k", hasTag = true , tag = 18 )
            pl512k , 
            @ASN1EnumItem ( name = "pl1024k", hasTag = true , tag = 19 )
            pl1024k , 
            @ASN1EnumItem ( name = "spare12", hasTag = true , tag = 20 )
            spare12 , 
            @ASN1EnumItem ( name = "spare11", hasTag = true , tag = 21 )
            spare11 , 
            @ASN1EnumItem ( name = "spare10", hasTag = true , tag = 22 )
            spare10 , 
            @ASN1EnumItem ( name = "spare9", hasTag = true , tag = 23 )
            spare9 , 
            @ASN1EnumItem ( name = "spare8", hasTag = true , tag = 24 )
            spare8 , 
            @ASN1EnumItem ( name = "spare7", hasTag = true , tag = 25 )
            spare7 , 
            @ASN1EnumItem ( name = "spare6", hasTag = true , tag = 26 )
            spare6 , 
            @ASN1EnumItem ( name = "spare5", hasTag = true , tag = 27 )
            spare5 , 
            @ASN1EnumItem ( name = "spare4", hasTag = true , tag = 28 )
            spare4 , 
            @ASN1EnumItem ( name = "spare3", hasTag = true , tag = 29 )
            spare3 , 
            @ASN1EnumItem ( name = "spare2", hasTag = true , tag = 30 )
            spare2 , 
            @ASN1EnumItem ( name = "spare1", hasTag = true , tag = 31 )
            spare1 , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RLC_BuffersPayload.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            