
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1Sequence;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "SatData", isSet = false )
    public class SatData implements IASN1PreparedElement {
            
        @ASN1Element ( name = "satID", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private SatID satID = null;
                
  
        @ASN1Element ( name = "iode", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private IODE iode = null;
                
  
        
        public SatID getSatID () {
            return this.satID;
        }

        

        public void setSatID (SatID value) {
            this.satID = value;
        }
        
  
        
        public IODE getIode () {
            return this.iode;
        }

        

        public void setIode (IODE value) {
            this.iode = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(SatData.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            