
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "SecurityCapability", isSet = false )
    public class SecurityCapability implements IASN1PreparedElement {
            @ASN1BitString( name = "" )
    
            @ASN1SizeConstraint ( max = 16L )
        
        @ASN1Element ( name = "cipheringAlgorithmCap", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private BitString cipheringAlgorithmCap = null;
                
  @ASN1BitString( name = "" )
    
            @ASN1SizeConstraint ( max = 16L )
        
        @ASN1Element ( name = "integrityProtectionAlgorithmCap", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private BitString integrityProtectionAlgorithmCap = null;
                
  
        
        public BitString getCipheringAlgorithmCap () {
            return this.cipheringAlgorithmCap;
        }

        

        public void setCipheringAlgorithmCap (BitString value) {
            this.cipheringAlgorithmCap = value;
        }
        
  
        
        public BitString getIntegrityProtectionAlgorithmCap () {
            return this.integrityProtectionAlgorithmCap;
        }

        

        public void setIntegrityProtectionAlgorithmCap (BitString value) {
            this.integrityProtectionAlgorithmCap = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(SecurityCapability.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            