
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "STARTSingle", isSet = false )
    public class STARTSingle implements IASN1PreparedElement {
            
        @ASN1Element ( name = "cn-DomainIdentity", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private CN_DomainIdentity cn_DomainIdentity = null;
                
  
        @ASN1Element ( name = "start-Value", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private START_Value start_Value = null;
                
  
        
        public CN_DomainIdentity getCn_DomainIdentity () {
            return this.cn_DomainIdentity;
        }

        

        public void setCn_DomainIdentity (CN_DomainIdentity value) {
            this.cn_DomainIdentity = value;
        }
        
  
        
        public START_Value getStart_Value () {
            return this.start_Value;
        }

        

        public void setStart_Value (START_Value value) {
            this.start_Value = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(STARTSingle.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            