
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "TrafficVolumeEventResults", isSet = false )
    public class TrafficVolumeEventResults implements IASN1PreparedElement {
            
        @ASN1Element ( name = "ul-transportChannelCausingEvent", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UL_TrCH_Identity ul_transportChannelCausingEvent = null;
                
  
        @ASN1Element ( name = "trafficVolumeEventIdentity", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private TrafficVolumeEventType trafficVolumeEventIdentity = null;
                
  
        
        public UL_TrCH_Identity getUl_transportChannelCausingEvent () {
            return this.ul_transportChannelCausingEvent;
        }

        

        public void setUl_transportChannelCausingEvent (UL_TrCH_Identity value) {
            this.ul_transportChannelCausingEvent = value;
        }
        
  
        
        public TrafficVolumeEventType getTrafficVolumeEventIdentity () {
            return this.trafficVolumeEventIdentity;
        }

        

        public void setTrafficVolumeEventIdentity (TrafficVolumeEventType value) {
            this.trafficVolumeEventIdentity = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TrafficVolumeEventResults.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            