
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "UE_Positioning_OTDOA_Measurement_v390ext", isSet = false )
    public class UE_Positioning_OTDOA_Measurement_v390ext implements IASN1PreparedElement {
            
        @ASN1Element ( name = "neighbourList-v390ext", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NeighbourList_v390ext neighbourList_v390ext = null;
                
  
        
        public NeighbourList_v390ext getNeighbourList_v390ext () {
            return this.neighbourList_v390ext;
        }

        

        public void setNeighbourList_v390ext (NeighbourList_v390ext value) {
            this.neighbourList_v390ext = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UE_Positioning_OTDOA_Measurement_v390ext.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            