
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "UE_PowerClassExt"
    )
    public class UE_PowerClassExt implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "class1", hasTag = true , tag = 0 )
            class1 , 
            @ASN1EnumItem ( name = "class2", hasTag = true , tag = 1 )
            class2 , 
            @ASN1EnumItem ( name = "class3", hasTag = true , tag = 2 )
            class3 , 
            @ASN1EnumItem ( name = "class4", hasTag = true , tag = 3 )
            class4 , 
            @ASN1EnumItem ( name = "spare4", hasTag = true , tag = 4 )
            spare4 , 
            @ASN1EnumItem ( name = "spare3", hasTag = true , tag = 5 )
            spare3 , 
            @ASN1EnumItem ( name = "spare2", hasTag = true , tag = 6 )
            spare2 , 
            @ASN1EnumItem ( name = "spare1", hasTag = true , tag = 7 )
            spare1 , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UE_PowerClassExt.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            