
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "UE_Positioning_GPS_NavModelAddDataReq", isSet = false )
    public class UE_Positioning_GPS_NavModelAddDataReq implements IASN1PreparedElement {
            @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 1023L 
		
	   )
	   
        @ASN1Element ( name = "gps-Week", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer gps_Week = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 255L 
		
	   )
	   
        @ASN1Element ( name = "gps-Toe", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer gps_Toe = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 15L 
		
	   )
	   
        @ASN1Element ( name = "tToeLimit", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer tToeLimit = null;
                
  
        @ASN1Element ( name = "satDataList", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private SatDataList satDataList = null;
                
  
        
        public Integer getGps_Week () {
            return this.gps_Week;
        }

        

        public void setGps_Week (Integer value) {
            this.gps_Week = value;
        }
        
  
        
        public Integer getGps_Toe () {
            return this.gps_Toe;
        }

        

        public void setGps_Toe (Integer value) {
            this.gps_Toe = value;
        }
        
  
        
        public Integer getTToeLimit () {
            return this.tToeLimit;
        }

        

        public void setTToeLimit (Integer value) {
            this.tToeLimit = value;
        }
        
  
        
        public SatDataList getSatDataList () {
            return this.satDataList;
        }

        

        public void setSatDataList (SatDataList value) {
            this.satDataList = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UE_Positioning_GPS_NavModelAddDataReq.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            