
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "UE_Positioning_Error", isSet = false )
    public class UE_Positioning_Error implements IASN1PreparedElement {
            
        @ASN1Element ( name = "errorReason", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UE_Positioning_ErrorCause errorReason = null;
                
  
        @ASN1Element ( name = "ue-positioning-GPS-additionalAssistanceDataRequest", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private UE_Positioning_GPS_AdditionalAssistanceDataRequest ue_positioning_GPS_additionalAssistanceDataRequest = null;
                
  
        
        public UE_Positioning_ErrorCause getErrorReason () {
            return this.errorReason;
        }

        

        public void setErrorReason (UE_Positioning_ErrorCause value) {
            this.errorReason = value;
        }
        
  
        
        public UE_Positioning_GPS_AdditionalAssistanceDataRequest getUe_positioning_GPS_additionalAssistanceDataRequest () {
            return this.ue_positioning_GPS_additionalAssistanceDataRequest;
        }

        
        public boolean isUe_positioning_GPS_additionalAssistanceDataRequestPresent () {
            return this.ue_positioning_GPS_additionalAssistanceDataRequest != null;
        }
        

        public void setUe_positioning_GPS_additionalAssistanceDataRequest (UE_Positioning_GPS_AdditionalAssistanceDataRequest value) {
            this.ue_positioning_GPS_additionalAssistanceDataRequest = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UE_Positioning_Error.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            