
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1Enum;
import org.bn.annotations.ASN1EnumItem;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1Sequence;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "UE_RadioAccessCapability_v690ext", isSet = false )
    public class UE_RadioAccessCapability_v690ext implements IASN1PreparedElement {
            
        @ASN1Element ( name = "physicalchannelcapability-edch", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private PhysicalChannelCapability_edch_r6 physicalchannelcapability_edch = null;
                
  

    @ASN1PreparedElement
    @ASN1Enum (
        name = "DeviceTypeEnumType"
    )
    public static class DeviceTypeEnumType implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "doesNotBenefitFromBatteryConsumptionOptimisation", hasTag = true , tag = 0 )
            doesNotBenefitFromBatteryConsumptionOptimisation , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DeviceTypeEnumType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

    }
                
        @ASN1Element ( name = "deviceType", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private DeviceTypeEnumType deviceType = null;
                
  
        
        public PhysicalChannelCapability_edch_r6 getPhysicalchannelcapability_edch () {
            return this.physicalchannelcapability_edch;
        }

        

        public void setPhysicalchannelcapability_edch (PhysicalChannelCapability_edch_r6 value) {
            this.physicalchannelcapability_edch = value;
        }
        
  
        
        public DeviceTypeEnumType getDeviceType () {
            return this.deviceType;
        }

        
        public boolean isDeviceTypePresent () {
            return this.deviceType != null;
        }
        

        public void setDeviceType (DeviceTypeEnumType value) {
            this.deviceType = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UE_RadioAccessCapability_v690ext.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            