
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "UE_RadioAccessCapability_v650ext", isSet = false )
    public class UE_RadioAccessCapability_v650ext implements IASN1PreparedElement {
            
        @ASN1Element ( name = "ue-RadioAccessCapabBandFDDList2", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UE_RadioAccessCapabBandFDDList2 ue_RadioAccessCapabBandFDDList2 = null;
                
  
        @ASN1Element ( name = "ue-RadioAccessCapabBandFDDList-ext", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private UE_RadioAccessCapabBandFDDList_ext ue_RadioAccessCapabBandFDDList_ext = null;
                
  
        
        public UE_RadioAccessCapabBandFDDList2 getUe_RadioAccessCapabBandFDDList2 () {
            return this.ue_RadioAccessCapabBandFDDList2;
        }

        

        public void setUe_RadioAccessCapabBandFDDList2 (UE_RadioAccessCapabBandFDDList2 value) {
            this.ue_RadioAccessCapabBandFDDList2 = value;
        }
        
  
        
        public UE_RadioAccessCapabBandFDDList_ext getUe_RadioAccessCapabBandFDDList_ext () {
            return this.ue_RadioAccessCapabBandFDDList_ext;
        }

        
        public boolean isUe_RadioAccessCapabBandFDDList_extPresent () {
            return this.ue_RadioAccessCapabBandFDDList_ext != null;
        }
        

        public void setUe_RadioAccessCapabBandFDDList_ext (UE_RadioAccessCapabBandFDDList_ext value) {
            this.ue_RadioAccessCapabBandFDDList_ext = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UE_RadioAccessCapability_v650ext.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            