
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "UE_RX_TX_TimeDifferenceType2Info", isSet = false )
    public class UE_RX_TX_TimeDifferenceType2Info implements IASN1PreparedElement {
            
        @ASN1Element ( name = "ue-RX-TX-TimeDifferenceType2", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private UE_RX_TX_TimeDifferenceType2 ue_RX_TX_TimeDifferenceType2 = null;
                
  
        @ASN1Element ( name = "neighbourQuality", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private NeighbourQuality neighbourQuality = null;
                
  
        
        public UE_RX_TX_TimeDifferenceType2 getUe_RX_TX_TimeDifferenceType2 () {
            return this.ue_RX_TX_TimeDifferenceType2;
        }

        

        public void setUe_RX_TX_TimeDifferenceType2 (UE_RX_TX_TimeDifferenceType2 value) {
            this.ue_RX_TX_TimeDifferenceType2 = value;
        }
        
  
        
        public NeighbourQuality getNeighbourQuality () {
            return this.neighbourQuality;
        }

        

        public void setNeighbourQuality (NeighbourQuality value) {
            this.neighbourQuality = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UE_RX_TX_TimeDifferenceType2Info.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            