
package org.amanzi.awe.l3messages.rrc;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1BoxedType;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1SequenceOf;
import org.bn.annotations.constraints.ASN1ValueRangeConstraint;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "UE_RadioAccessCapabBandFDDList" )
    public class UE_RadioAccessCapabBandFDDList implements IASN1PreparedElement {
                
            @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 8L 
		
	   )
	   
            @ASN1SequenceOf( name = "UE-RadioAccessCapabBandFDDList" , isSetOf = false)
	    private java.util.Collection<UE_RadioAccessCapabBandFDD> value = null; 
    
            public UE_RadioAccessCapabBandFDDList () {
            }
        
            public UE_RadioAccessCapabBandFDDList ( java.util.Collection<UE_RadioAccessCapabBandFDD> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<UE_RadioAccessCapabBandFDD> value) {
                this.value = value;
            }
            
            public java.util.Collection<UE_RadioAccessCapabBandFDD> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<UE_RadioAccessCapabBandFDD>()); 
            }
            
            public void add(UE_RadioAccessCapabBandFDD item) {
                value.add(item);
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UE_RadioAccessCapabBandFDDList.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            