/* AWE - Amanzi Wireless Explorer
 * http://awe.amanzi.org
 * (C) 2008-2009, AmanziTel AB
 *
 * This library is provided under the terms of the Eclipse Public License
 * as described at http://www.eclipse.org/legal/epl-v10.html. Any use,
 * reproduction or distribution of the library constitutes recipient's
 * acceptance of this agreement.
 *
 * This library is distributed WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

package org.amanzi.neo.core.enums.gpeh;

/**
 * <p>
 * GPEH parameters
 * </p>
 * 
 * @author Cinkel_A
 * @since 1.0.0
 */
public enum Parameters {
    EVENT_PARAM_ACT_REASON(3),
    EVENT_PARAM_ACTION(7),
    EVENT_PARAM_ASE_REDUCTION(17),
    EVENT_PARAM_NO_OF_CELLS_IN_ACTIVE_SET(3),
    EVENT_PARAM_NO_OF_CELLS_IN_REPORT(3),
    EVENT_PARAM_CHANNEL_SWITCH_REASON(5),
    EVENT_PARAM_CHANNEL_SWITCH_RESULT(2),
    EVENT_PARAM_CHANNELIZATION_CODE_NORM_MODE(9),
    EVENT_PARAM_CHANNELIZATION_CODE_COMP_MODE(9),
    EVENT_PARAM_CM_TYPE(3),
    EVENT_PARAM_CURRENT_STATE(3),
    EVENT_PARAM_DL_TFCI_D_1(16),
    EVENT_PARAM_DL_TFCI_D_2(16),
    EVENT_PARAM_DL_TFCI_D_3(16),
    EVENT_PARAM_DL_TFCI_D_4(16),
    EVENT_PARAM_DL_TFCI_D_5(16),
    EVENT_PARAM_DL_TFCI_D_6(16),
    EVENT_PARAM_DL_TFCI_D_7(16),
    EVENT_PARAM_DL_TFCI_D_8(16),
    EVENT_PARAM_DL_TFCI_D_9(16),
    EVENT_PARAM_DL_TFCI_D_10(16),
    EVENT_PARAM_DL_TFCI_D_11(16),
    EVENT_PARAM_DL_TFCI_D_12(16),
    EVENT_PARAM_DL_TFCI_D_13(16),
    EVENT_PARAM_DL_TFCI_D_14(16),
    EVENT_PARAM_DL_TFCI_D_15(16),
    EVENT_PARAM_DL_TFCI_D_16(16),
    EVENT_PARAM_DL_TFCI_D_17(16),
    EVENT_PARAM_DL_TFCI_D_18(16),
    EVENT_PARAM_DL_TFCI_D_19(16),
    EVENT_PARAM_DL_TFCI_D_20(16),
    EVENT_PARAM_DL_TFCI_D_21(16),
    EVENT_PARAM_DL_TFCI_D_22(16),
    EVENT_PARAM_DL_TFCI_D_23(16),
    EVENT_PARAM_DL_TFCI_D_24(16),
    EVENT_PARAM_DL_TFCI_D_25(16),
    EVENT_PARAM_DL_TFCI_D_26(16),
    EVENT_PARAM_DL_TFCI_D_27(16),
    EVENT_PARAM_DL_TFCI_D_28(16),
    EVENT_PARAM_DL_TFCI_D_29(16),
    EVENT_PARAM_DL_TFCI_D_30(16),
    EVENT_PARAM_DL_TFCI_D_31(16),
    EVENT_PARAM_DL_TFCI_D_32(16),
    EVENT_PARAM_UL_TFI1_D_1(16),
    EVENT_PARAM_UL_TFI1_D_2(16),
    EVENT_PARAM_UL_TFI1_D_3(16),
    EVENT_PARAM_UL_TFI1_D_4(16),
    EVENT_PARAM_UL_TFI1_D_5(16),
    EVENT_PARAM_UL_TFI1_D_6(16),
    EVENT_PARAM_UL_TFI1_D_7(16),
    EVENT_PARAM_UL_TFI1_D_8(16),
    EVENT_PARAM_UL_TFI1_D_9(16),
    EVENT_PARAM_UL_TFI1_D_10(16),
    EVENT_PARAM_UL_TFI1_D_11(16),
    EVENT_PARAM_UL_TFI1_D_12(16),
    EVENT_PARAM_UL_TFI1_D_13(16),
    EVENT_PARAM_UL_TFI1_D_14(16),
    EVENT_PARAM_UL_TFI1_D_15(16),
    EVENT_PARAM_UL_TFI1_D_16(16),
    EVENT_PARAM_UL_TFI1_D_17(16),
    EVENT_PARAM_UL_TFI1_D_18(16),
    EVENT_PARAM_UL_TFI1_D_19(16),
    EVENT_PARAM_UL_TFI1_D_20(16),
    EVENT_PARAM_UL_TFI1_D_21(16),
    EVENT_PARAM_UL_TFI1_D_22(16),
    EVENT_PARAM_UL_TFI1_D_23(16),
    EVENT_PARAM_UL_TFI1_D_24(16),
    EVENT_PARAM_UL_TFI1_D_25(16),
    EVENT_PARAM_UL_TFI1_D_26(16),
    EVENT_PARAM_UL_TFI1_D_27(16),
    EVENT_PARAM_UL_TFI1_D_28(16),
    EVENT_PARAM_UL_TFI1_D_29(16),
    EVENT_PARAM_UL_TFI1_D_30(16),
    EVENT_PARAM_UL_TFI1_D_31(16),
    EVENT_PARAM_UL_TFI1_D_32(16),
    EVENT_PARAM_UL_TFI_D2_1(16),
    EVENT_PARAM_UL_TFI_D2_2(16),
    EVENT_PARAM_UL_TFI_D3_1(16),
    EVENT_PARAM_UL_TFI_D3_2(16),
    EVENT_PARAM_UL_TFI_S_1(16),
    EVENT_PARAM_UL_TFI_S_2(16),
    EVENT_PARAM_UL_TFI_S_3(16),
    EVENT_PARAM_UL_TFI_S_4(16),
    EVENT_PARAM_UL_TFI_S_5(16),
    EVENT_PARAM_UL_TFI_S_6(16),
    EVENT_PARAM_UL_TFI_S_7(16),
    EVENT_PARAM_UL_TFI_S_8(16),
    EVENT_PARAM_UL_TFI_S_9(16),
    EVENT_PARAM_UL_TFI_S_10(16),
    EVENT_PARAM_UL_TFI_S_11(16),
    EVENT_PARAM_UL_TFI_S_12(16),
    EVENT_PARAM_UL_TFI_S_13(16),
    EVENT_PARAM_UL_TFI_S_14(16),
    EVENT_PARAM_UL_TFI_S_15(16),
    EVENT_PARAM_UL_TFI_S_16(16),
    EVENT_PARAM_UL_TFI_S_17(16),
    EVENT_PARAM_UL_TFI_S_18(16),
    EVENT_PARAM_UL_TFI_S_19(16),
    EVENT_PARAM_UL_TFI_S_20(16),
    EVENT_PARAM_UL_TFI_S_21(16),
    EVENT_PARAM_UL_TFI_S_22(16),
    EVENT_PARAM_UL_TFI_S_23(16),
    EVENT_PARAM_UL_TFI_S_24(16),
    EVENT_PARAM_UL_TFI_S_25(16),
    EVENT_PARAM_UL_TFI_S_26(16),
    EVENT_PARAM_UL_TFI_S_27(16),
    EVENT_PARAM_UL_TFI_S_28(16),
    EVENT_PARAM_UL_TFI_S_29(16),
    EVENT_PARAM_UL_TFI_S_30(16),
    EVENT_PARAM_UL_TFI_S_31(16),
    EVENT_PARAM_UL_TFI_S_32(16),
    EVENT_PARAM_DEACT_REASON(3),
    EVENT_PARAM_DL_POWER(8),
    EVENT_PARAM_ESTIMATED_POWER(8),
    EVENT_PARAM_EVENT_TRIGGER(7),
    EVENT_PARAM_FAILURE_REASON(8),
    EVENT_PARAM_CPICH_EC_NO_CELL_1(7),
    EVENT_PARAM_CPICH_EC_NO_CELL_2(7),
    EVENT_PARAM_CPICH_EC_NO_CELL_3(7),
    EVENT_PARAM_CPICH_EC_NO_CELL_4(7),
    EVENT_PARAM_CPICH_EC_NO_EVAL_CELL(7),
    EVENT_PARAM_RSCP_CELL_1(8),
    EVENT_PARAM_RSCP_CELL_2(8),
    EVENT_PARAM_RSCP_CELL_3(8),
    EVENT_PARAM_RSCP_CELL_4(8),
    EVENT_PARAM_RSCP_EVAL_CELL(8),
    EVENT_PARAM_SCRAMBLING_CODE_CELL_1(10),
    EVENT_PARAM_SCRAMBLING_CODE_CELL_2(10),
    EVENT_PARAM_SCRAMBLING_CODE_CELL_3(10),
    EVENT_PARAM_SCRAMBLING_CODE_CELL_4(10),
    EVENT_PARAM_SCRAMBLING_CODE_EVAL_CELL_1(10),
    EVENT_PARAM_SCRAMBLING_CODE_EVAL_CELL_2(10),
    EVENT_PARAM_SCRAMBLING_CODE_EVAL_CELL_3(10),
    EVENT_PARAM_SCRAMBLING_CODE_EVAL_CELL_4(10),
    //TODO check parsing parameter EVENT_PARAM_IMSI
    EVENT_PARAM_IMSI(60,Rules.LONG),
    EVENT_PARAM_MEAS_REPORTS_IN_BUFFER_1A_1C(5),
    EVENT_PARAM_MEAS_REPORTS_IN_BUFFER_1B(5),
    EVENT_PARAM_MEAS_REPORTS_IN_BUFFER_1D(5),
    EVENT_PARAM_MEAS_REPORTS_IN_BUFFER_3A(5),
    EVENT_PARAM_MEASURED_ENTITY(4),
    EVENT_PARAM_MEASURED_VALUE(11),
    EVENT_PARAM_NO_OF_BE_USERS_TO_BE_SWITCHED(8),
    EVENT_PARAM_NO_OF_BE_USERS_TO_BE_SWITCHED_IUR(8),
    EVENT_PARAM_NR_OF_CONNECTIONS_SF8(8),
    EVENT_PARAM_NR_OF_CONNECTIONS_SF16(8),
    EVENT_PARAM_NR_OF_CONNECTIONS_SF32(8),
    PARAM_NR_OF_GUAR_DATA_USERS_TO_BE_TERMINATED(8),
    PARAM_NR_OF_GUAR_DATA_USERS_TO_BE_TERMINATED_IUR(8),
    EVENT_PARAM_NO_OF_SPEECH_USERS_TO_BE_TERMINATED(8),
    EVENT_PARAM_NO_OF_SPEECH_USERS_TO_BE_TERMINATED_IUR(8),
    EVENT_PARAM_PREVIOUS_STATE(3),
    EVENT_PARAM_RAB_DATA_RATE(3),
    EVENT_PARAM_RESULT(3),
    EVENT_PARAM_RLC_BUFFER_VOLUME(16),
    EVENT_PARAM_CELL_UPDATE_CAUSE_VALUE(4),
    EVENT_PARAM_STATE_CHANGE_NODE(3),
    EVENT_PARAM_TOTAL_ASE_DL(17),
    EVENT_PARAM_TOTAL_ASE_UL(17),
    EVENT_PARAM_TOTAL_DL_CHAN_CODE_TREE_CONSUMPTION(16),
    EVENT_PARAM_UE_CONTEXT(16),
    EVENT_PARAM_UL_INTERFERENCE(11),
    EVENT_PARAM_UL_SIR_TARGET(9),
    EVENT_PARAM_VALUE_AT_FAILURE(24),
    EVENT_PARAM_RNC_MODULE_ID(7),
    EVENT_PARAM_EVENT_ID(11),
    EVENT_PARAM_TIMESTAMP_HOUR(6),
    EVENT_PARAM_TIMESTAMP_MINUTE(6),
    EVENT_PARAM_TIMESTAMP_SECOND(6),
    EVENT_PARAM_TIMESTAMP_MILLISEC(11),
    EVENT_PARAM_ERROR_TYPE(6),
    EVENT_PARAM_PROTOCOL_ERROR_CAUSE(16),
    EVENT_PARAM_RRC_TRANSACTION_IDENTIFIER(16),
    EVENT_PARAM_PROCEDURE_CODE(16),
    EVENT_PARAM_RECEIVED_MESSAGE_TYPE(16),
    EVENT_PARAM_IE_NAME(17),
    EVENT_PARAM_ERROR_LOCATION(256,Rules.STRING),
    EVENT_PARAM_ASN1_AVAILABILITY(2),
    EVENT_PARAM_MESSAGE_LENGTH(12),
    EVENT_PARAM_MESSAGE_DISCRIMINATOR(16),
    EVENT_PARAM_CN_DOMAIN_INDICATOR(16),
    EVENT_PARAM_HANDOVER_TYPE(3),
    EVENT_PARAM_PDU_TYPE(5),
    EVENT_PARAM_MESSAGE_DIRECTION(2),
    EVENT_PARAM_MESSAGE_CONTENTS(16384,Rules.STRING),
    EVENT_PARAM_NO_OF_CM_USERS(8),
    EVENT_PARAM_REQUEST_TYPE(3),
    EVENT_PARAM_TRAFFIC_CLASS(3),
    EVENT_PARAM_TRAFFIC_CLASS_UL(4),
    EVENT_PARAM_NO_OF_TRANSPORT_BEARERS(17),
    EVENT_PARAM_NO_OF_IUR_FACH_FRAMES_PRIO_1(17),
    EVENT_PARAM_NO_OF_IUR_FACH_FRAMES_PRIO_2(17),
    EVENT_PARAM_NO_OF_IUR_FACH_FRAMES_PRIO_3(17),
    EVENT_PARAM_NO_OF_IUR_FACH_FRAMES_PRIO_4(17),
    EVENT_PARAM_NO_OF_IUR_FACH_FRAMES_PRIO_1_DISC(17),
    EVENT_PARAM_NO_OF_IUR_FACH_FRAMES_PRIO_2_DISC(17),
    EVENT_PARAM_NO_OF_IUR_FACH_FRAMES_PRIO_3_DISC(17),
    EVENT_PARAM_NO_OF_IUR_FACH_FRAMES_PRIO_4_DISC(17),
    EVENT_PARAM_C_ID_1(17),
    EVENT_PARAM_C_ID_2(17),
    EVENT_PARAM_C_ID_3(17),
    EVENT_PARAM_C_ID_4(17),
    EVENT_PARAM_C_ID_EVALUATED(17),
    EVENT_PARAM_RNC_ID_1(13),
    EVENT_PARAM_RNC_ID_2(13),
    EVENT_PARAM_RNC_ID_3(13),
    EVENT_PARAM_RNC_ID_4(13),
    EVENT_PARAM_RNC_ID_EVALUATED(13),
    EVENT_PARAM_GSM_C_I(17),
    EVENT_PARAM_GSM_LAC(25),
    EVENT_PARAM_GSM_PLMN_ID(17),
    EVENT_PARAM_GSM_RSSI(7),
    EVENT_PARAM_IRAT_CELL_ID_1(6),
    EVENT_PARAM_IRAT_CELL_ID_2(6),
    EVENT_PARAM_IRAT_CELL_ID_3(6),
    EVENT_PARAM_IRAT_CELL_ID_4(6),
    EVENT_PARAM_RLS_ID_1(6),
    EVENT_PARAM_RLS_ID_2(6),
    EVENT_PARAM_RLS_ID_3(6),
    EVENT_PARAM_RLS_ID_4(6),
    EVENT_PARAM_RLS_TAG_1(2),
    EVENT_PARAM_RLS_TAG_2(2),
    EVENT_PARAM_RLS_TAG_3(2),
    EVENT_PARAM_RLS_TAG_4(2),
    EVENT_PARAM_UL_SCRAMBLING_CODE(25),
    EVENT_PARAM_SPREADING_FACTOR_NORM_MODE(10),
    EVENT_PARAM_SPREADING_FACTOR_COMP_MODE(10),
    EVENT_PARAM_CHANGED_NODE_SPREADING_FACTOR(10),
    EVENT_PARAM_CHANGED_NODE_CODE_NUMBER(9),
    EVENT_PARAM_CODE_TREE_LOAD(10),
    EVENT_PARAM_SCRAMBLING_CODE_REP_CELL_1(10),
    EVENT_PARAM_UARFCN_DL_REP_CELL_1(16),
    EVENT_PARAM_UARFCN_UL_REP_CELL_1(16),
    EVENT_PARAM_SCRAMBLING_CODE_REP_CELL_2(10),
    EVENT_PARAM_UARFCN_DL_REP_CELL_2(16),
    EVENT_PARAM_UARFCN_UL_REP_CELL_2(16),
    EVENT_PARAM_SCRAMBLING_CODE_REP_CELL_3(10),
    EVENT_PARAM_UARFCN_DL_REP_CELL_3(16),
    EVENT_PARAM_UARFCN_UL_REP_CELL_3(16),
    EVENT_PARAM_SCRAMBLING_CODE_REP_CELL_4(10),
    EVENT_PARAM_UARFCN_DL_REP_CELL_4(16),
    EVENT_PARAM_UARFCN_UL_REP_CELL_4(16),
    EVENT_PARAM_MEAS_REPORTS_IN_BUFFER_2B(2),
    EVENT_PARAM_C_ID_NU_FREQ(17),
    EVENT_PARAM_RNC_ID_NU_FREQ(13),
    EVENT_PARAM_CPICH_EC_NU_FREQ_CELL(7),
    EVENT_PARAM_RSCP_NU_FREQ_CELL(8),
    EVENT_PARAM_RNC_MP_ID(7),
    EVENT_PARAM_SCRAMBLING_CODE_TRIGGER_CELL(10),
    EVENT_PARAM_CPICH_EC_NO_TRIGGER_CELL(7),
    EVENT_PARAM_RSCP_TRIGGER_CELL(8),
    EVENT_PARAM_SCRAMBLING_CODE_ADDITIONAL_CELL1(10),
    EVENT_PARAM_CPICH_EC_NO_ADDITIONAL_CELL1(7),
    EVENT_PARAM_RSCP_ADDITIONAL_CELL1(8),
    EVENT_PARAM_SCRAMBLING_CODE_ADDITIONAL_CELL2(10),
    EVENT_PARAM_CPICH_EC_NO_ADDITIONAL_CELL2(7),
    EVENT_PARAM_RSCP_ADDITIONAL_CELL2(8),
    EVENT_PARAM_C_ID_TRIGGER_CELL(17),
    EVENT_PARAM_RNC_ID_TRIGGER_CELL(13),
    EVENT_PARAM_UE_POS_METHOD(3),
    EVENT_PARAM_NR_GPS_SATELLITES(6),
    EVENT_PARAM_MEASUREMENT_TIME(10),
    EVENT_PARAM_REQUIRED_HORIZONTAL_ACCURACY(8),
    EVENT_PARAM_ACHIEVED_HORIZONTAL_ACCURACY(8),
    EVENT_PARAM_REQUIRED_VERTICAL_ACCURACY(8),
    EVENT_PARAM_ACHIEVED_VERTICAL_ACCURACY(9),
    EVENT_PARAM_UE_REFERENCE_POSITION(2),
    EVENT_PARAM_LATITUDE_SIGN(2),
    EVENT_PARAM_LATITUDE(24),
    EVENT_PARAM_LONGITUDE_SIGN(2),
    EVENT_PARAM_LONGITUDE(25),
    EVENT_PARAM_ALTITUDE_DIRECTION(2),
    EVENT_PARAM_UNCERTAINTY_SEMI_MAJOR(8),
    EVENT_PARAM_UNCERTAINTY_SEMI_MINOR(8),
    EVENT_PARAM_ORIENTATION_MAJOR_AXIS(9),
    EVENT_PARAM_CONFIDENCE(8),
    EVENT_PARAM_HS_DSCH_PHYSICAL_LAYER_CATEGORY(8),
    EVENT_PARAM_E_DCH_PHYSICAL_LAYER_CATEGORY(8),
    EVENT_PARAM_E_DCH_AND_OR_HS_DSCH_CELL_ID(17),
    EVENT_PARAM_REQUESTED_SERVICE_CLASS(3),
    EVENT_PARAM_REQUESTED_SETUP_CLASS(2),
    EVENT_PARAM_REQUESTED_ORIGIN(2),
    EVENT_PARAM_REQUESTED_SF_DL(10),
    EVENT_PARAM_REQUESTED_SF_UL(10),
    EVENT_PARAM_REQUESTED_COMPRESSED_MODE(2),
    EVENT_PARAM_REQUESTED_RAB_STATE(6),
    EVENT_PARAM_CURRENT_SF_DL(10),
    EVENT_PARAM_CURRENT_SF_UL(10),
    EVENT_PARAM_CURRENT_RAB_STATE(6),
    EVENT_PARAM_BLOCKING_PROCEDURE(4),
    EVENT_PARAM_BLOCK_REASON(5),
    EVENT_PARAM_BLOCK_TYPE(4),
    EVENT_PARAM_BLOCK_ADMISSION_POLICY_LEVEL(10),
    EVENT_PARAM_LOCAL_CELL_GROUP_ID(29),
    EVENT_PARAM_RBS_ID(32),
    EVENT_PARAM_CAPACITY_CREDITS_UL(17),
    EVENT_PARAM_CAPACITY_CREDITS_DL(17),
    EVENT_PARAM_CONSUMED_CREDITS_UL(18),
    EVENT_PARAM_CONSUMED_CREDITS_DL(18),
    EVENT_PARAM_C_ID_SOURCE(17),
    EVENT_PARAM_CPICH_EC_NO_SOURCE_CELL(7),
    EVENT_PARAM_CPICH_RSCP_SOURCE_CELL(8),
    EVENT_PARAM_C_ID_TARGET(17),
    EVENT_PARAM_CPICH_EC_NO_TARGET_CELL(7),
    EVENT_PARAM_CPICH_RSCP_TARGET_CELL(8),
    EVENT_PARAM_SELECTED_CELL(2),
    EVENT_PARAM_PATHLOSS(10),
    EVENT_PARAM_UARFCN_SOURCE(15),
    EVENT_PARAM_UARFCN_TARGET(15),
    EVENT_PARAM_UL_SYNC_STATUS_RLS1(2),
    EVENT_PARAM_NO_OF_HS_USERS_TO_BE_TERMINATED_IUR(10),
    EVENT_PARAM_NO_OF_EUL_USERS_TO_BE_SWITCHED(10),
    EVENT_PARAM_NUMBER_OF_USERS_ASSIGNED_TO_PHYS_HS_CHAN(10),
    EVENT_PARAM_NUMBER_OF_EDCH_USERS_IN_SERVING_CELL(8),
    EVENT_PARAM_NUMBER_OF_EDCH_USERS_IN_NON_SERVING_CELL(10),
    EVENT_PARAM_NR_OF_CONNECTIONS_SF4_UL(8),
    EVENT_PARAM_PROTOCOL_ID(4),
    EVENT_PARAM_UE_POS_UNSUCC_CAUSE(5),
    EVENT_PARAM_NO_OF_PS_STREAMING_USERS_TO_BE_TERMINATED(8),
    EVENT_PARAM_NO_OF_PS_STREAMING_USERS_TO_BE_TERMINATED_IUR(8),
    EVENT_PARAM_UARFCN_DL_NON_USED_FREQ_1(15),
    EVENT_PARAM_UARFCN_DL_NON_USED_FREQ_2(15),
    EVENT_PARAM_UARFCN_DL_NON_USED_FREQ_3(15),
    EVENT_PARAM_NR_OF_GUAR_DATA_USERS_TO_BE_TERMINATED(8),
    EVENT_PARAM_NR_OF_GUAR_DATA_USERS_TO_BE_TERMINATED_IUR(8),
    EVENT_PARAM_TRIGGER_POINT(3),
    EVENT_PARAM_RAN_DISCONNECTION_CODE(6),
    EVENT_PARAM_RAN_DISCONNECTION_SUBCODE(5),
    EVENT_PARAM_RAN_ID_PARAMETER(17),
    EVENT_PARAM_CPM(3),
    EVENT_PARAM_SCRAMBLING_CODE_ADDED_CELL(10),
    EVENT_PARAM_CPICH_EC_NO_ADDED_CELL(7),
    EVENT_PARAM_RSCP_CELL_1_ADDED_CELL(8),
    EVENT_PARAM_CNHHO_TYPE(2),
    EVENT_PARAM_IUR_STATUS(2),
    EVENT_PARAM_RAB_DATA_RATE_UL(15),
    EVENT_PARAM_RAB_DATA_RATE_DL(15),
    EVENT_PARAM_UL_THROUGHPUT(15),
    EVENT_PARAM_DL_THROUGHPUT(15),
    EVENT_PARAM_NR_OF_CONNECTIONS_SF8_UL(8),
    EVENT_PARAM_NR_OF_CONNECTIONS_SF16_UL(8),
    EVENT_PARAM_SOURCE_CONF(8),
    EVENT_PARAM_TARGET_CONF(8),
    EVENT_PARAM_TARGET_CAP(2),
    EVENT_PARAM_UEPOS_INITIAL_CONF(8),
    EVENT_PARAM_UEPOS_FINAL_CONF(8),
    //TODO not in bitpack
    EVENT_PARAM_MEASUREMENT_TYPE(1*8),
  //TODO not in bitpack
    EVENT_PARAM_MEASUREMENT_LENGTH(2*8),
    EVENT_PARAM_UL_INT_CELL1(11),
    EVENT_PARAM_UL_INT_CELL2(11),
    EVENT_PARAM_UL_INT_CELL3(11),
    EVENT_PARAM_UL_INT_CELL4(11),
    EVENT_PARAM_C_ID_SERV_HSDSCH_CELL(17),
    EVENT_PARAM_CRNC_ID_SERV_HSDSCH_CELL(13),
    EVENT_PARAM_EC_NO_SERV_HSDSCH_CELL(7),
    EVENT_PARAM_RSCP_SERV_HSDSCH_CELL(8),
    EVENT_PARAM_AFFECTED_SCANNER_TYPE(3),
    EVENT_PARAM_NO_OF_HS_USERS_TO_BE_SWITCHED(10),
    EVENT_PARAM_URA_ID(17),
    EVENT_PARAM_E_DCH_AND_OR_HS_DSCH_CELL_SELECTION_RESULT(4),
    EVENT_PARAM_CN_ID(2);
    private final int bits;
    private final Rules rule;

    /**
     * constructor
     */
    private Parameters(int bits) {
        this.bits = bits;
        rule = Rules.INTEGER;
    }

    /**
     * constructor
     * 
     * @param bits length
     * @param rule - interpretation rule
     */
    private Parameters(int bits, Rules rule) {
        this.bits = bits;
        this.rule = rule;
    }

    /**
     * <p>
     * interpretation rules
     * </p>
     * 
     * @author Cinkel_A
     * @since 1.0.0
     */
    public enum Rules {
        INTEGER, STRING, LONG;
    }

    /**
     * @return
     */
    public int getBitsLen() {
        return bits;
    }

    /**
     * @param bitSet
     * @return
     */
    public Object pareseBits(String bitSet) {
        switch (rule) {
        case INTEGER:
            return Integer.valueOf(bitSet, 2);
        case LONG:
            return Long.valueOf(bitSet, 2);
        case STRING:
            // TODO change to normal text!
            return bitSet;
        default:
            return null;
        }
    }

    /**
     * @return Returns the rule.
     */
    public Rules getRule() {
        return rule;
    }
    
}
