//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.02 at 04:34:44 PM MSK 
//


package org.amanzi.neo.model.distribution.xml.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.distributionxmlschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Distribution_QNAME = new QName("http://www.example.org/DistributionXMLSchema", "distribution");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.distributionxmlschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link Distribution }
     * 
     */
    public Distribution createDistribution() {
        return new Distribution();
    }

    /**
     * Create an instance of {@link Color }
     * 
     */
    public Color createColor() {
        return new Color();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Bars }
     * 
     */
    public Bars createBars() {
        return new Bars();
    }

    /**
     * Create an instance of {@link Bar }
     * 
     */
    public Bar createBar() {
        return new Bar();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Distribution }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/DistributionXMLSchema", name = "distribution")
    public JAXBElement<Distribution> createDistribution(Distribution value) {
        return new JAXBElement<Distribution>(_Distribution_QNAME, Distribution.class, null, value);
    }

}
